package gcn

import (
	"fmt"
	"strings"

	"go101.org/nstd"
)

var Mnemotics = map[Encoding]map[uint32]string{
	EncSOP2: {
		Sop2OpAddU32:       "s_add_u32",
		Sop2OpSubU32:       "s_sub_u32",
		Sop2OpAddI32:       "s_add_i32",
		Sop2OpSubI32:       "s_sub_i32",
		Sop2OpAddcU32:      "s_addc_u32",
		Sop2OpSubbU32:      "s_subb_u32",
		Sop2OpMinI32:       "s_min_i32",
		Sop2OpMinU32:       "s_min_u32",
		Sop2OpMaxI32:       "s_max_i32",
		Sop2OpMaxU32:       "s_max_u32",
		Sop2OpCselectB32:   "s_cselect_b32",
		Sop2OpCselectB64:   "s_cselect_b64",
		Sop2OpAndB32:       "s_and_b32",
		Sop2OpAndB64:       "s_and_b64",
		Sop2OpOrB32:        "s_or_b32",
		Sop2OpOrB64:        "s_or_b64",
		Sop2OpXorB32:       "s_xor_b32",
		Sop2OpXorB64:       "s_xor_b64",
		Sop2OpAndn2B32:     "s_andn2_b32",
		Sop2OpAndn2B64:     "s_andn2_b64",
		Sop2OpOrn2B32:      "s_orn2_b32",
		Sop2OpOrn2B64:      "s_orn2_b64",
		Sop2OpNandB32:      "s_nand_b32",
		Sop2OpNandB64:      "s_nand_b64",
		Sop2OpNorB32:       "s_nor_b32",
		Sop2OpNorB64:       "s_nor_b64",
		Sop2OpXnorB32:      "s_xnor_b32",
		Sop2OpXnorB64:      "s_xnor_b64",
		Sop2OpLshlB32:      "s_lshl_b32",
		Sop2OpLshlB64:      "s_lshl_b64",
		Sop2OpLshrB32:      "s_lshr_b32",
		Sop2OpLshrB64:      "s_lshr_b64",
		Sop2OpAshrI32:      "s_ashr_i32",
		Sop2OpAshrI64:      "s_ashr_i64",
		Sop2OpBfmB32:       "s_bfm_b32",
		Sop2OpBfmB64:       "s_bfm_b64",
		Sop2OpMulI32:       "s_mul_i32",
		Sop2OpBfeU32:       "s_bfe_u32",
		Sop2OpBfeI32:       "s_bfe_i32",
		Sop2OpBfeU64:       "s_bfe_u64",
		Sop2OpBfeI64:       "s_bfe_i64",
		Sop2OpCbranchGFork: "s_cbranch_g_fork",
		Sop2OpAbsdiffI32:   "s_absdiff_i32",
	},
	EncSOPK: {
		SopkOpMovkI32:        "s_movk_i32",
		SopkOpCmovkI32:       "s_cmovk_i32",
		SopkOpCmpkEqI32:      "s_cmpk_eq_i32",
		SopkOpCmpkLgI32:      "s_cmpk_lg_i32",
		SopkOpCmpkGtI32:      "s_cmpk_gt_i32",
		SopkOpCmpkGeI32:      "s_cmpk_ge_i32",
		SopkOpCmpkLtI32:      "s_cmpk_lt_i32",
		SopkOpCmpkLeI32:      "s_cmpk_le_i32",
		SopkOpCmpkEqU32:      "s_cmpk_eq_u32",
		SopkOpCmpkLgU32:      "s_cmpk_lg_u32",
		SopkOpCmpkGtU32:      "s_cmpk_gt_u32",
		SopkOpCmpkGeU32:      "s_cmpk_ge_u32",
		SopkOpCmpkLtU32:      "s_cmpk_lt_u32",
		SopkOpCmpkLeU32:      "s_cmpk_le_u32",
		SopkOpAddkI32:        "s_addk_i32",
		SopkOpMulkI32:        "s_mulk_i32",
		SopkOpCbranchIFork:   "s_cbranch_i_fork",
		SopkOpGetregB32:      "s_getreg_b32",
		SopkOpSetregB32:      "s_setreg_b32",
		SopkOpSetregImm32B32: "s_setreg_imm32_b32",
	},
	EncSOP1: {
		Sop1OpMovB32:           "s_mov_b32",
		Sop1OpMovB64:           "s_mov_b64",
		Sop1OpCmovB32:          "s_cmov_b32",
		Sop1OpCmovB64:          "s_cmov_b64",
		Sop1OpNotB32:           "s_not_b32",
		Sop1OpNotB64:           "s_not_b64",
		Sop1OpWqmB32:           "s_wqm_b32",
		Sop1OpWqmB64:           "s_wqm_b64",
		Sop1OpBrevB32:          "s_brev_b32",
		Sop1OpBrevB64:          "s_brev_b64",
		Sop1OpBcnt0I32B32:      "s_bcnt0_i32_b32",
		Sop1OpBcnt0I32B64:      "s_bcnt0_i32_b64",
		Sop1OpBcnt1I32B32:      "s_bcnt1_i32_b32",
		Sop1OpBcnt1I32B64:      "s_bcnt1_i32_b64",
		Sop1OpFf0I32B32:        "s_ff0_i32_b32",
		Sop1OpFf0I32B64:        "s_ff0_i32_b64",
		Sop1OpFf1I32B32:        "s_ff1_i32_b32",
		Sop1OpFf1I32B64:        "s_ff1_i32_b64",
		Sop1OpFlbitI32B32:      "s_flbit_i32_b32",
		Sop1OpFlbitI32B64:      "s_flbit_i32_b64",
		Sop1OpBitset0B32:       "s_bitset0_b32",
		Sop1OpBitset0B64:       "s_bitset0_b64",
		Sop1OpBitset1B32:       "s_bitset1_b32",
		Sop1OpBitset1B64:       "s_bitset1_b64",
		Sop1OpGetpcB64:         "s_getpc_b64",
		Sop1OpSetpcB64:         "s_setpc_b64",
		Sop1OpSwappcB64:        "s_swappc_b64",
		Sop1OpRfeB64:           "s_rfe_b64",
		Sop1OpFlbitI32:         "s_flbit_i32",
		Sop1OpFlbitI32I64:      "s_flbit_i32_i64",
		Sop1OpAndSaveexecB64:   "s_and_saveexec_b64",
		Sop1OpOrSaveexecB64:    "s_or_saveexec_b64",
		Sop1OpSextI32I8:        "s_sext_i32_i8",
		Sop1OpSextI32I16:       "s_sext_i32_i16",
		Sop1OpXnorSaveexecB64:  "s_xnor_saveexec_b64",
		Sop1OpQuadmaskB32:      "s_quadmask_b32",
		Sop1OpQuadmaskB64:      "s_quadmask_b64",
		Sop1OpMovrelsB32:       "s_movrels_b32",
		Sop1OpMovrelsB64:       "s_movrels_b64",
		Sop1OpMovreldB32:       "s_movreld_b32",
		Sop1OpMovreldB64:       "s_movreld_b64",
		Sop1OpCbranchJoin:      "s_cbranch_join",
		Sop1OpAbsI32:           "s_abs_i32",
		Sop1OpXorSaveexecB64:   "s_xor_saveexec_b64",
		Sop1OpAndn2SaveexecB64: "s_andn2_saveexec_b64",
		Sop1OpOrn2SaveexecB64:  "s_orn2_saveexec_b64",
		Sop1OpNandSaveexecB64:  "s_nand_saveexec_b64",
		Sop1OpNorSaveexecB64:   "s_nor_saveexec_b64",
	},
	EncSOPC: {
		SopcOpCmpEqI32:   "s_cmp_eq_i32",
		SopcOpCmpLgI32:   "s_cmp_lg_i32",
		SopcOpCmpGtI32:   "s_cmp_gt_i32",
		SopcOpCmpGeI32:   "s_cmp_ge_i32",
		SopcOpCmpLtI32:   "s_cmp_lt_i32",
		SopcOpCmpLeI32:   "s_cmp_le_i32",
		SopcOpCmpEqU32:   "s_cmp_eq_u32",
		SopcOpCmpLgU32:   "s_cmp_lg_u32",
		SopcOpCmpGtU32:   "s_cmp_gt_u32",
		SopcOpCmpGeU32:   "s_cmp_ge_u32",
		SopcOpCmpLtU32:   "s_cmp_lt_u32",
		SopcOpCmpLeU32:   "s_cmp_le_u32",
		SopcOpBitcmp0B32: "s_bitcmp0_b32",
		SopcOpBitcmp1B32: "s_bitcmp1_b32",
		SopcOpBitcmp0B64: "s_bitcmp0_b64",
		SopcOpBitcmp1B64: "s_bitcmp1_b64",
		SopcOpSetvskip:   "s_setvskip",
	},
	EncSOPP: {
		SoppOpNop:                   "s_nop",
		SoppOpEndpgm:                "s_endpgm",
		SoppOpBranch:                "s_branch",
		SoppOpCbranchScc0:           "s_cbranch_scc0",
		SoppOpCbranchScc1:           "s_cbranch_scc1",
		SoppOpCbranchVccz:           "s_cbranch_vccz",
		SoppOpCbranchVccnz:          "s_cbranch_vccnz",
		SoppOpCbranchExecz:          "s_cbranch_execz",
		SoppOpCbranchExecnz:         "s_cbranch_execnz",
		SoppOpBarrier:               "s_barrier",
		SoppOpSetkill:               "s_setkill",
		SoppOpWaitcnt:               "s_waitcnt",
		SoppOpSethalt:               "s_sethalt",
		SoppOpSleep:                 "s_sleep",
		SoppOpSetprio:               "s_setprio",
		SoppOpSendmsg:               "s_sendmsg",
		SoppOpSendmsghalt:           "s_sendmsghalt",
		SoppOpTrap:                  "s_trap",
		SoppOpIcacheInv:             "s_icache_inv",
		SoppOpIncperflevel:          "s_incperflevel",
		SoppOpDecperflevel:          "s_decperflevel",
		SoppOpTtraceData:            "s_ttracedata",
		SoppOpCbranchCdbgsys:        "s_cbranch_cdbgsys",
		SoppOpCbranchCdbguser:       "s_cbranch_cdbguser",
		SoppOpCbranchCdbgsysOrUser:  "s_cbranch_cdbgsys_or_user",
		SoppOpCbranchCdbgsysAndUser: "s_cbranch_cdbgsys_and_user",
	},
	EncVOP2: {
		Vop2OpCndmaskB32:      "v_cndmask_b32",
		Vop2OpReadlaneB32:     "v_readlane_b32",
		Vop2OpWritelaneB32:    "v_writelane_b32",
		Vop2OpAddF32:          "v_add_f32",
		Vop2OpSubF32:          "v_sub_f32",
		Vop2OpSubrevF32:       "v_subrev_f32",
		Vop2OpMacLegacyF32:    "v_mac_legacy_f32",
		Vop2OpMulLegacyF32:    "v_mul_legacy_f32",
		Vop2OpMulF32:          "v_mul_f32",
		Vop2OpMulI32I24:       "v_mul_i32_i24",
		Vop2OpMulHiI32I24:     "v_mul_hi_i32_i24",
		Vop2OpMulU32U24:       "v_mul_u32_u24",
		Vop2OpMulHiU32U24:     "v_mul_hi_u32_u24",
		Vop2OpMinLegacyF32:    "v_min_legacy_f32",
		Vop2OpMaxLegacyF32:    "v_max_legacy_f32",
		Vop2OpMinF32:          "v_min_f32",
		Vop2OpMaxF32:          "v_max_f32",
		Vop2OpMinI32:          "v_min_i32",
		Vop2OpMaxI32:          "v_max_i32",
		Vop2OpMinU32:          "v_min_u32",
		Vop2OpMaxU32:          "v_max_u32",
		Vop2OpLshrB32:         "v_lshr_b32",
		Vop2OpLshrrevB32:      "v_lshrrev_b32",
		Vop2OpAshrI32:         "v_ashr_i32",
		Vop2OpAshrrevI32:      "v_ashrrev_i32",
		Vop2OpLshlB32:         "v_lshl_b32",
		Vop2OpLshlrevB32:      "v_lshlrev_b32",
		Vop2OpAndB32:          "v_and_b32",
		Vop2OpOrB32:           "v_or_b32",
		Vop2OpXorB32:          "v_xor_b32",
		Vop2OpBfmB32:          "v_bfm_b32",
		Vop2OpMacF32:          "v_mac_f32",
		Vop2OpMadmkF32:        "v_madmk_f32",
		Vop2OpMadakF32:        "v_madak_f32",
		Vop2OpBcntU32B32:      "v_bcnt_u32_b32",
		Vop2OpMbcntLoU32B32:   "v_mbcnt_lo_u32_b32",
		Vop2OpMbcntHiU32B32:   "v_mbcnt_hi_u32_b32",
		Vop2OpAddI32:          "v_add_i32",
		Vop2OpSubI32:          "v_sub_i32",
		Vop2OpSubrevI32:       "v_subrev_i32",
		Vop2OpAddcU32:         "v_addc_u32",
		Vop2OpSubbU32:         "v_subb_u32",
		Vop2OpSubbrevU32:      "v_subbrev_u32",
		Vop2OpLdexpF32:        "v_ldexp_f32",
		Vop2OpCvtPkaccumU8F32: "v_cvt_pkaccum_u8_f32",
		Vop2OpCvtPknormI16F32: "v_cvt_pknorm_i16_f32",
		Vop2OpCvtPknormU16F32: "v_cvt_pknorm_u16_f32",
		Vop2OpCvtPkrtzF16F32:  "v_cvt_pkrtz_f16_f32",
		Vop2OpCvtPkU16U32:     "v_cvt_pk_u16_u32",
		Vop2OpCvtPkI16I32:     "v_cvt_pk_i16_i32",
	},
	EncVOP1: {
		Vop1OpNop:              "v_nop",
		Vop1OpMovB32:           "v_mov_b32",
		Vop1OpReadfirstlaneB32: "v_readfirstlane_b32",
		Vop1OpCvtI32F64:        "v_cvt_i32_f64",
		Vop1OpCvtF64I32:        "v_cvt_f64_i32",
		Vop1OpCvtF32I32:        "v_cvt_f32_i32",
		Vop1OpCvtF32U32:        "v_cvt_f32_u32",
		Vop1OpCvtU32F32:        "v_cvt_u32_f32",
		Vop1OpCvtI32F32:        "v_cvt_i32_f32",
		Vop1OpCvtF16F32:        "v_cvt_f16_f32",
		Vop1OpCvtF32F16:        "v_cvt_f32_f16",
		Vop1OpCvtRpiI32F32:     "v_cvt_rpi_i32_f32",
		Vop1OpCvtFlrI32F32:     "v_cvt_flr_i32_f32",
		Vop1OpCvtOffF32I4:      "v_cvt_off_f32_i4",
		Vop1OpCvtF32F64:        "v_cvt_f32_f64",
		Vop1OpCvtF64F32:        "v_cvt_f64_f32",
		Vop1OpCvtF32Ubyte0:     "v_cvt_f32_ubyte0",
		Vop1OpCvtF32Ubyte1:     "v_cvt_f32_ubyte1",
		Vop1OpCvtF32Ubyte2:     "v_cvt_f32_ubyte2",
		Vop1OpCvtF32Ubyte3:     "v_cvt_f32_ubyte3",
		Vop1OpCvtU32F64:        "v_cvt_u32_f64",
		Vop1OpCvtF64U32:        "v_cvt_f64_u32",
		Vop1OpTruncF64:         "v_trunc_f64",
		Vop1OpCeilF64:          "v_ceil_f64",
		Vop1OpRndneF64:         "v_rndne_f64",
		Vop1OpFloorF64:         "v_floor_f64",
		Vop1OpFractF32:         "v_fract_f32",
		Vop1OpTruncF32:         "v_trunc_f32",
		Vop1OpCeilF32:          "v_ceil_f32",
		Vop1OpRndneF32:         "v_rndne_f32",
		Vop1OpFloorF32:         "v_floor_f32",
		Vop1OpExpF32:           "v_exp_f32",
		Vop1OpLogClampF32:      "v_log_clamp_f32",
		Vop1OpLogF32:           "v_log_f32",
		Vop1OpRcpF32:           "v_rcp_f32",
		Vop1OpRcpClampF32:      "v_rcp_clamp_f32",
		Vop1OpRsqLegacyF32:     "v_rsq_legacy_f32",
		Vop1OpRsqF32:           "v_rsq_f32",
		Vop1OpRcpF64:           "v_rcp_f64",
		Vop1OpRcpClampF64:      "v_rcp_clamp_f64",
		Vop1OpRsqF64:           "v_rsq_f64",
		Vop1OpRsqClampF64:      "v_rsq_clamp_f64",
		Vop1OpSqrtF32:          "v_sqrt_f32",
		Vop1OpSqrtF64:          "v_sqrt_f64",
		Vop1OpSinF32:           "v_sin_f32",
		Vop1OpCosF32:           "v_cos_f32",
		Vop1OpNotB32:           "v_not_b32",
		Vop1OpBfrevB32:         "v_bfrev_b32",
		Vop1OpFfbhU32:          "v_ffbh_u32",
		Vop1OpFfblB32:          "v_ffbl_b32",
		Vop1OpFfbhI32:          "v_ffbh_i32",
		Vop1OpFrexpExpI32F64:   "v_frexp_exp_i32_f64",
		Vop1OpFrexpMantF64:     "v_frexp_mant_f64",
		Vop1OpFractF64:         "v_fract_f64",
		Vop1OpFrexpExpI32F32:   "v_frexp_exp_i32_f32",
		Vop1OpFrexpMantF32:     "v_frexp_mant_f32",
		Vop1OpClrexcp:          "v_clrexcp",
		Vop1OpMovreldB32:       "v_movreld_b32",
		Vop1OpMovrelsB32:       "v_movrels_b32",
		Vop1OpMovrelsdB32:      "v_movrelsd_b32",
		Vop1OpLogLegacyF32:     "v_log_legacy_f32",
		Vop1OpExpLegacyF32:     "v_exp_legacy_f32",
	},
	EncVOPC: {
		VopcOpCmpFF32:      "v_cmp_f_f32",
		VopcOpCmpLtF32:     "v_cmp_lt_f32",
		VopcOpCmpEqF32:     "v_cmp_eq_f32",
		VopcOpCmpLeF32:     "v_cmp_le_f32",
		VopcOpCmpGtF32:     "v_cmp_gt_f32",
		VopcOpCmpLgF32:     "v_cmp_lg_f32",
		VopcOpCmpGeF32:     "v_cmp_ge_f32",
		VopcOpCmpOF32:      "v_cmp_o_f32",
		VopcOpCmpUF32:      "v_cmp_u_f32",
		VopcOpCmpNgeF32:    "v_cmp_nge_f32",
		VopcOpCmpNlgF32:    "v_cmp_nlg_f32",
		VopcOpCmpNgtF32:    "v_cmp_ngt_f32",
		VopcOpCmpNleF32:    "v_cmp_nle_f32",
		VopcOpCmpNeqF32:    "v_cmp_neq_f32",
		VopcOpCmpNltF32:    "v_cmp_nlt_f32",
		VopcOpCmpTruF32:    "v_cmp_tru_f32",
		VopcOpCmpxFF32:     "v_cmpx_f_f32",
		VopcOpCmpxLtF32:    "v_cmpx_lt_f32",
		VopcOpCmpxEqF32:    "v_cmpx_eq_f32",
		VopcOpCmpxLeF32:    "v_cmpx_le_f32",
		VopcOpCmpxGtF32:    "v_cmpx_gt_f32",
		VopcOpCmpxLgF32:    "v_cmpx_lg_f32",
		VopcOpCmpxGeF32:    "v_cmpx_ge_f32",
		VopcOpCmpxOF32:     "v_cmpx_o_f32",
		VopcOpCmpxUF32:     "v_cmpx_u_f32",
		VopcOpCmpxNgeF32:   "v_cmpx_nge_f32",
		VopcOpCmpxNlgF32:   "v_cmpx_nlg_f32",
		VopcOpCmpxNgtF32:   "v_cmpx_ngt_f32",
		VopcOpCmpxNleF32:   "v_cmpx_nle_f32",
		VopcOpCmpxNeqF32:   "v_cmpx_neq_f32",
		VopcOpCmpxNltF32:   "v_cmpx_nlt_f32",
		VopcOpCmpxTruF32:   "v_cmpx_tru_f32",
		VopcOpCmpFF64:      "v_cmp_f_f64",
		VopcOpCmpLtF64:     "v_cmp_lt_f64",
		VopcOpCmpEqF64:     "v_cmp_eq_f64",
		VopcOpCmpLeF64:     "v_cmp_le_f64",
		VopcOpCmpGtF64:     "v_cmp_gt_f64",
		VopcOpCmpLgF64:     "v_cmp_lg_f64",
		VopcOpCmpGeF64:     "v_cmp_ge_f64",
		VopcOpCmpOF64:      "v_cmp_o_f64",
		VopcOpCmpUF64:      "v_cmp_u_f64",
		VopcOpCmpNgeF64:    "v_cmp_nge_f64",
		VopcOpCmpNlgF64:    "v_cmp_nlg_f64",
		VopcOpCmpNgtF64:    "v_cmp_ngt_f64",
		VopcOpCmpNleF64:    "v_cmp_nle_f64",
		VopcOpCmpNeqF64:    "v_cmp_neq_f64",
		VopcOpCmpNltF64:    "v_cmp_nlt_f64",
		VopcOpCmpTruF64:    "v_cmp_tru_f64",
		VopcOpCmpxFF64:     "v_cmpx_f_f64",
		VopcOpCmpxLtF64:    "v_cmpx_lt_f64",
		VopcOpCmpxEqF64:    "v_cmpx_eq_f64",
		VopcOpCmpxLeF64:    "v_cmpx_le_f64",
		VopcOpCmpxGtF64:    "v_cmpx_gt_f64",
		VopcOpCmpxLgF64:    "v_cmpx_lg_f64",
		VopcOpCmpxGeF64:    "v_cmpx_ge_f64",
		VopcOpCmpxOF64:     "v_cmpx_o_f64",
		VopcOpCmpxUF64:     "v_cmpx_u_f64",
		VopcOpCmpxNgeF64:   "v_cmpx_nge_f64",
		VopcOpCmpxNlgF64:   "v_cmpx_nlg_f64",
		VopcOpCmpxNgtF64:   "v_cmpx_ngt_f64",
		VopcOpCmpxNleF64:   "v_cmpx_nle_f64",
		VopcOpCmpxNeqF64:   "v_cmpx_neq_f64",
		VopcOpCmpxNltF64:   "v_cmpx_nlt_f64",
		VopcOpCmpxTruF64:   "v_cmpx_tru_f64",
		VopcOpCmpSFF32:     "v_cmps_f_f32",
		VopcOpCmpSLtF32:    "v_cmps_lt_f32",
		VopcOpCmpSEqF32:    "v_cmps_eq_f32",
		VopcOpCmpSLeF32:    "v_cmps_le_f32",
		VopcOpCmpSGtF32:    "v_cmps_gt_f32",
		VopcOpCmpSLgF32:    "v_cmps_lg_f32",
		VopcOpCmpSGeF32:    "v_cmps_ge_f32",
		VopcOpCmpSOF32:     "v_cmps_o_f32",
		VopcOpCmpSUF32:     "v_cmps_u_f32",
		VopcOpCmpSNgeF32:   "v_cmps_nge_f32",
		VopcOpCmpSNlgF32:   "v_cmps_nlg_f32",
		VopcOpCmpSNgtF32:   "v_cmps_ngt_f32",
		VopcOpCmpSNleF32:   "v_cmps_nle_f32",
		VopcOpCmpSNeqF32:   "v_cmps_neq_f32",
		VopcOpCmpSNltF32:   "v_cmps_nlt_f32",
		VopcOpCmpSTruF32:   "v_cmps_tru_f32",
		VopcOpCmpsxFF32:    "v_cmpsx_f_f32",
		VopcOpCmpsxLtF32:   "v_cmpsx_lt_f32",
		VopcOpCmpsxEqF32:   "v_cmpsx_eq_f32",
		VopcOpCmpsxLeF32:   "v_cmpsx_le_f32",
		VopcOpCmpsxGtF32:   "v_cmpsx_gt_f32",
		VopcOpCmpsxLgF32:   "v_cmpsx_lg_f32",
		VopcOpCmpsxGeF32:   "v_cmpsx_ge_f32",
		VopcOpCmpsxOF32:    "v_cmpsx_o_f32",
		VopcOpCmpsxUF32:    "v_cmpsx_u_f32",
		VopcOpCmpsxNgeF32:  "v_cmpsx_nge_f32",
		VopcOpCmpsxNlgF32:  "v_cmpsx_nlg_f32",
		VopcOpCmpsxNgtF32:  "v_cmpsx_ngt_f32",
		VopcOpCmpsxNleF32:  "v_cmpsx_nle_f32",
		VopcOpCmpsxNeqF32:  "v_cmpsx_neq_f32",
		VopcOpCmpsxNltF32:  "v_cmpsx_nlt_f32",
		VopcOpCmpsxTruF32:  "v_cmpsx_tru_f32",
		VopcOpCmpSFF64:     "v_cmps_f_f64",
		VopcOpCmpSLtF64:    "v_cmps_lt_f64",
		VopcOpCmpSEqF64:    "v_cmps_eq_f64",
		VopcOpCmpSLeF64:    "v_cmps_le_f64",
		VopcOpCmpSGtF64:    "v_cmps_gt_f64",
		VopcOpCmpSLgF64:    "v_cmps_lg_f64",
		VopcOpCmpSGeF64:    "v_cmps_ge_f64",
		VopcOpCmpSOF64:     "v_cmps_o_f64",
		VopcOpCmpSUF64:     "v_cmps_u_f64",
		VopcOpCmpSNgeF64:   "v_cmps_nge_f64",
		VopcOpCmpSNlgF64:   "v_cmps_nlg_f64",
		VopcOpCmpSNgtF64:   "v_cmps_ngt_f64",
		VopcOpCmpSNleF64:   "v_cmps_nle_f64",
		VopcOpCmpSNeqF64:   "v_cmps_neq_f64",
		VopcOpCmpSNltF64:   "v_cmps_nlt_f64",
		VopcOpCmpSTruF64:   "v_cmps_tru_f64",
		VopcOpCmpsxFF64:    "v_cmpsx_f_f64",
		VopcOpCmpsxLtF64:   "v_cmpsx_lt_f64",
		VopcOpCmpsxEqF64:   "v_cmpsx_eq_f64",
		VopcOpCmpsxLeF64:   "v_cmpsx_le_f64",
		VopcOpCmpsxGtF64:   "v_cmpsx_gt_f64",
		VopcOpCmpsxLgF64:   "v_cmpsx_lg_f64",
		VopcOpCmpsxGeF64:   "v_cmpsx_ge_f64",
		VopcOpCmpsxOF64:    "v_cmpsx_o_f64",
		VopcOpCmpsxUF64:    "v_cmpsx_u_f64",
		VopcOpCmpsxNgeF64:  "v_cmpsx_nge_f64",
		VopcOpCmpsxNlgF64:  "v_cmpsx_nlg_f64",
		VopcOpCmpsxNgtF64:  "v_cmpsx_ngt_f64",
		VopcOpCmpsxNleF64:  "v_cmpsx_nle_f64",
		VopcOpCmpsxNeqF64:  "v_cmpsx_neq_f64",
		VopcOpCmpsxNltF64:  "v_cmpsx_nlt_f64",
		VopcOpCmpsxTruF64:  "v_cmpsx_tru_f64",
		VopcOpCmpFI32:      "v_cmp_f_i32",
		VopcOpCmpLtI32:     "v_cmp_lt_i32",
		VopcOpCmpEqI32:     "v_cmp_eq_i32",
		VopcOpCmpLeI32:     "v_cmp_le_i32",
		VopcOpCmpGtI32:     "v_cmp_gt_i32",
		VopcOpCmpLgI32:     "v_cmp_lg_i32",
		VopcOpCmpGeI32:     "v_cmp_ge_i32",
		VopcOpCmpTruI32:    "v_cmp_tru_i32",
		VopcOpCmpxFI32:     "v_cmpx_f_i32",
		VopcOpCmpxLtI32:    "v_cmpx_lt_i32",
		VopcOpCmpxEqI32:    "v_cmpx_eq_i32",
		VopcOpCmpxLeI32:    "v_cmpx_le_i32",
		VopcOpCmpxGtI32:    "v_cmpx_gt_i32",
		VopcOpCmpxLgI32:    "v_cmpx_lg_i32",
		VopcOpCmpxGeI32:    "v_cmpx_ge_i32",
		VopcOpCmpxTruI32:   "v_cmpx_tru_i32",
		VopcOpCmpFI64:      "v_cmp_f_i64",
		VopcOpCmpLtI64:     "v_cmp_lt_i64",
		VopcOpCmpEqI64:     "v_cmp_eq_i64",
		VopcOpCmpLeI64:     "v_cmp_le_i64",
		VopcOpCmpGtI64:     "v_cmp_gt_i64",
		VopcOpCmpLgI64:     "v_cmp_lg_i64",
		VopcOpCmpGeI64:     "v_cmp_ge_i64",
		VopcOpCmpTruI64:    "v_cmp_tru_i64",
		VopcOpCmpxFI64:     "v_cmpx_f_i64",
		VopcOpCmpxLtI64:    "v_cmpx_lt_i64",
		VopcOpCmpxEqI64:    "v_cmpx_eq_i64",
		VopcOpCmpxLeI64:    "v_cmpx_le_i64",
		VopcOpCmpxGtI64:    "v_cmpx_gt_i64",
		VopcOpCmpxLgI64:    "v_cmpx_lg_i64",
		VopcOpCmpxGeI64:    "v_cmpx_ge_i64",
		VopcOpCmpxTruI64:   "v_cmpx_tru_i64",
		VopcOpCmpFU32:      "v_cmp_f_u32",
		VopcOpCmpLtU32:     "v_cmp_lt_u32",
		VopcOpCmpEqU32:     "v_cmp_eq_u32",
		VopcOpCmpLeU32:     "v_cmp_le_u32",
		VopcOpCmpGtU32:     "v_cmp_gt_u32",
		VopcOpCmpLgU32:     "v_cmp_lg_u32",
		VopcOpCmpGeU32:     "v_cmp_ge_u32",
		VopcOpCmpTruU32:    "v_cmp_tru_u32",
		VopcOpCmpxFU32:     "v_cmpx_f_u32",
		VopcOpCmpxLtU32:    "v_cmpx_lt_u32",
		VopcOpCmpxEqU32:    "v_cmpx_eq_u32",
		VopcOpCmpxLeU32:    "v_cmpx_le_u32",
		VopcOpCmpxGtU32:    "v_cmpx_gt_u32",
		VopcOpCmpxLgU32:    "v_cmpx_lg_u32",
		VopcOpCmpxGeU32:    "v_cmpx_ge_u32",
		VopcOpCmpxTruU32:   "v_cmpx_tru_u32",
		VopcOpCmpFU64:      "v_cmp_f_u64",
		VopcOpCmpLtU64:     "v_cmp_lt_u64",
		VopcOpCmpEqU64:     "v_cmp_eq_u64",
		VopcOpCmpLeU64:     "v_cmp_le_u64",
		VopcOpCmpGtU64:     "v_cmp_gt_u64",
		VopcOpCmpLgU64:     "v_cmp_lg_u64",
		VopcOpCmpGeU64:     "v_cmp_ge_u64",
		VopcOpCmpTruU64:    "v_cmp_tru_u64",
		VopcOpCmpxFU64:     "v_cmpx_f_u64",
		VopcOpCmpxLtU64:    "v_cmpx_lt_u64",
		VopcOpCmpxEqU64:    "v_cmpx_eq_u64",
		VopcOpCmpxLeU64:    "v_cmpx_le_u64",
		VopcOpCmpxGtU64:    "v_cmpx_gt_u64",
		VopcOpCmpxLgU64:    "v_cmpx_lg_u64",
		VopcOpCmpxGeU64:    "v_cmpx_ge_u64",
		VopcOpCmpxTruU64:   "v_cmpx_tru_u64",
		VopcOpCmpClassF32:  "v_cmp_class_f32",
		VopcOpCmpxClassF32: "v_cmpx_class_f32",
		VopcOpCmpClassF64:  "v_cmp_class_f64",
		VopcOpCmpxClassF64: "v_cmpx_class_f64",
	},
	EncVINTRP: {
		VintrpOpInterpP1F32:  "v_interp_p1_f32",
		VintrpOpInterpP2F32:  "v_interp_p2_f32",
		VintrpOpInterpMovF32: "v_interp_mov_f32",
	},
	EncVOP3: {
		// VOP2 opcodes.
		Vop3OpCndmaskB32:      "v_cndmask_b32",
		Vop3OpReadlaneB32:     "v_readlane_b32",
		Vop3OpWritelaneB32:    "v_writelane_b32",
		Vop3OpAddF32:          "v_add_f32",
		Vop3OpSubF32:          "v_sub_f32",
		Vop3OpSubrevF32:       "v_subrev_f32",
		Vop3OpMacLegacyF32:    "v_mac_legacy_f32",
		Vop3OpMulLegacyF32:    "v_mul_legacy_f32",
		Vop3OpMulF32:          "v_mul_f32",
		Vop3OpMulI32I24:       "v_mul_i32_i24",
		Vop3OpMulHiI32I24:     "v_mul_hi_i32_i24",
		Vop3OpMulU32U24:       "v_mul_u32_u24",
		Vop3OpMulHiU32U24:     "v_mul_hi_u32_u24",
		Vop3OpMinLegacyF32:    "v_min_legacy_f32",
		Vop3OpMaxLegacyF32:    "v_max_legacy_f32",
		Vop3OpMinF32:          "v_min_f32",
		Vop3OpMaxF32:          "v_max_f32",
		Vop3OpMinI32:          "v_min_i32",
		Vop3OpMaxI32:          "v_max_i32",
		Vop3OpMinU32:          "v_min_u32",
		Vop3OpMaxU32:          "v_max_u32",
		Vop3OpLshrB32:         "v_lshr_b32",
		Vop3OpLshrrevB32:      "v_lshrrev_b32",
		Vop3OpAshrI32:         "v_ashr_i32",
		Vop3OpAshrrevI32:      "v_ashrrev_i32",
		Vop3OpLshlB32:         "v_lshl_b32",
		Vop3OpLshlrevB32:      "v_lshlrev_b32",
		Vop3OpAndB32:          "v_and_b32",
		Vop3OpOrB32:           "v_or_b32",
		Vop3OpXorB32:          "v_xor_b32",
		Vop3OpBfmB32:          "v_bfm_b32",
		Vop3OpMacF32:          "v_mac_f32",
		Vop3OpBcntU32B32:      "v_bcnt_u32_b32",
		Vop3OpMbcntHiU32B32:   "v_mbcnt_hi_u32_b32",
		Vop3OpAddI32:          "v_add_i32",
		Vop3OpSubI32:          "v_sub_i32",
		Vop3OpSubrevI32:       "v_subrev_i32",
		Vop3OpAddcU32:         "v_addc_u32",
		Vop3OpSubbU32:         "v_subb_u32",
		Vop3OpSubbrevU32:      "v_subbrev_u32",
		Vop3OpLdexpF32:        "v_ldexp_f32",
		Vop3OpCvtPkaccumU8F32: "v_cvt_pkaccum_u8_f32",
		Vop3OpCvtPknormI16F32: "v_cvt_pknorm_i16_f32",
		Vop3OpCvtPknormU16F32: "v_cvt_pknorm_u16_f32",
		Vop3OpCvtPkrtzF16F32:  "v_cvt_pkrtz_f16_f32",
		Vop3OpCvtPkU16U32:     "v_cvt_pk_u16_u32",
		Vop3OpCvtPkI16I32:     "v_cvt_pk_i16_i32",

		// VOP3 opcodes.
		Vop3OpMadLegacyF32: "v_mad_legacy_f32",
		Vop3OpMadF32:       "v_mad_f32",
		Vop3OpMadI32I24:    "v_mad_i32_i24",
		Vop3OpMadU32U24:    "v_mad_u32_u24",
		Vop3OpCubeidF32:    "v_cubeid_f32",
		Vop3OpCubescF32:    "v_cubesc_f32",
		Vop3OpCubetcF32:    "v_cubetc_f32",
		Vop3OpCubemaF32:    "v_cubema_f32",
		Vop3OpBfeU32:       "v_bfe_u32",
		Vop3OpBfeI32:       "v_bfe_i32",
		Vop3OpBfiB32:       "v_bfi_b32",
		Vop3OpFmaF32:       "v_fma_f32",
		Vop3OpFmaF64:       "v_fma_f64",
		Vop3OpLerpU8:       "v_lerp_u8",
		Vop3OpAlignbitB32:  "v_alignbit_b32",
		Vop3OpAlignbyteB32: "v_alignbyte_b32",
		Vop3OpMullitF32:    "v_mullit_f32",
		Vop3OpMin3F32:      "v_min3_f32",
		Vop3OpMin3I32:      "v_min3_i32",
		Vop3OpMin3U32:      "v_min3_u32",
		Vop3OpMax3F32:      "v_max3_f32",
		Vop3OpMax3I32:      "v_max3_i32",
		Vop3OpMax3U32:      "v_max3_u32",
		Vop3OpMed3F32:      "v_med3_f32",
		Vop3OpMed3I32:      "v_med3_i32",
		Vop3OpMed3U32:      "v_med3_u32",
		Vop3OpSadU8:        "v_sad_u8",
		Vop3OpSadHiU8:      "v_sad_hi_u8",
		Vop3OpSadU16:       "v_sad_u16",
		Vop3OpSadU32:       "v_sad_u32",
		Vop3OpCvtPkU8F32:   "v_cvt_pk_u8_f32",
		Vop3OpDivFixupF32:  "v_div_fixup_f32",
		Vop3OpDivFixupF64:  "v_div_fixup_f64",
		Vop3OpLshlB64:      "v_lshl_b64",
		Vop3OpLshrB64:      "v_lshr_b64",
		Vop3OpAshrI64:      "v_ashr_i64",
		Vop3OpAddF64:       "v_add_f64",
		Vop3OpMulF64:       "v_mul_f64",
		Vop3OpMin3F64:      "v_min3_f64",
		Vop3OpMaxF64:       "v_max_f64",
		Vop3OpLdexpF64:     "v_ldexp_f64",
		Vop3OpMulLoU32:     "v_mul_lo_u32",
		Vop3OpMulHiU32:     "v_mul_hi_u32",
		Vop3OpMulLoI32:     "v_mul_lo_i32",
		Vop3OpMulHiI32:     "v_mul_hi_i32",
		Vop3OpDivScaleF32:  "v_div_scale_f32",
		Vop3OpDivScaleF64:  "v_div_scale_f64",
		Vop3OpDivFmasF32:   "v_div_fmas_f32",
		Vop3OpDivFmasF64:   "v_div_fmas_f64",
		Vop3OpMsadU8:       "v_msad_u8",
		Vop3OpQsadPkU16U8:  "v_qsad_pk_u16_u8",
		Vop3OpMqsadPkU16U8: "v_mqsad_pk_u16_u8",
		Vop3OpTrigPreopF64: "v_trig_preop_f64",
		Vop3OpMqsadU32U8:   "v_mqsad_u32_u8",
		Vop3OpMadU64U32:    "v_mad_u64_u32",
		Vop3OpMadI64I32:    "v_mad_i64_i32",

		// VOP1 opcodes.
		Vop3OpNop:              "v_nop",
		Vop3OpMovB32:           "v_mov_b32",
		Vop3OpReadfirstlaneB32: "v_readfirstlane_b32",
		Vop3OpCvtI32F64:        "v_cvt_i32_f64",
		Vop3OpCvtF64I32:        "v_cvt_f64_i32",
		Vop3OpCvtF32I32:        "v_cvt_f32_i32",
		Vop3OpCvtF32U32:        "v_cvt_f32_u32",
		Vop3OpCvtU32F32:        "v_cvt_u32_f32",
		Vop3OpCvtI32F32:        "v_cvt_i32_f32",
		Vop3OpCvtF16F32:        "v_cvt_f16_f32",
		Vop3OpCvtF32F16:        "v_cvt_f32_f16",
		Vop3OpCvtRpiI32F32:     "v_cvt_rpi_i32_f32",
		Vop3OpCvtFlrI32F32:     "v_cvt_flr_i32_f32",
		Vop3OpCvtOffF32I4:      "v_cvt_off_f32_i4",
		Vop3OpCvtF32F64:        "v_cvt_f32_f64",
		Vop3OpCvtF64F32:        "v_cvt_f64_f32",
		Vop3OpCvtF32Ubyte0:     "v_cvt_f32_ubyte0",
		Vop3OpCvtF32Ubyte1:     "v_cvt_f32_ubyte1",
		Vop3OpCvtF32Ubyte2:     "v_cvt_f32_ubyte2",
		Vop3OpCvtF32Ubyte3:     "v_cvt_f32_ubyte3",
		Vop3OpCvtU32F64:        "v_cvt_u32_f64",
		Vop3OpCvtF64U32:        "v_cvt_f64_u32",
		Vop3OpFractF32:         "v_fract_f32",
		Vop3OpTruncF32:         "v_trunc_f32",
		Vop3OpCeilF32:          "v_ceil_f32",
		Vop3OpRndneF32:         "v_rndne_f32",
		Vop3OpFloorF32:         "v_floor_f32",
		Vop3OpExpF32:           "v_exp_f32",
		Vop3OpLogClampF32:      "v_log_clamp_f32",
		Vop3OpLogF32:           "v_log_f32",
		Vop3OpRcpClampF32:      "v_rcp_clamp_f32",
		Vop3OpRcpLegacyF32:     "v_rcp_legacy_f32",
		Vop3OpRcpF32:           "v_rcp_f32",
		Vop3OpRcpIflagF32:      "v_rcp_iflag_f32",
		Vop3OpRsqClampF32:      "v_rsq_clamp_f32",
		Vop3OpRsqLegacyF32:     "v_rsq_legacy_f32",
		Vop3OpRsqF32:           "v_rsq_f32",
		Vop3OpRcpF64:           "v_rcp_f64",
		Vop3OpRcpClampF64:      "v_rcp_clamp_f64",
		Vop3OpRsqF64:           "v_rsq_f64",
		Vop3OpRsqClampF64:      "v_rsq_clamp_f64",
		Vop3OpSqrtF32:          "v_sqrt_f32",
		Vop3OpSqrtF64:          "v_sqrt_f64",
		Vop3OpSinF32:           "v_sin_f32",
		Vop3OpCosF32:           "v_cos_f32",
		Vop3OpNotB32:           "v_not_b32",
		Vop3OpBfrevB32:         "v_bfrev_b32",
		Vop3OpFfbhU32:          "v_ffbh_u32",
		Vop3OpFfblB32:          "v_ffbl_b32",
		Vop3OpFfbhI32:          "v_ffbh_i32",
		Vop3OpFrexpExpI32F64:   "v_frexp_exp_i32_f64",
		Vop3OpFrexpMantF64:     "v_frexp_mant_f64",
		Vop3OpFractF64:         "v_fract_f64",
		Vop3OpFrexpExpI32F32:   "v_frexp_exp_i32_f32",
		Vop3OpFrexpMantF32:     "v_frexp_mant_f32",
		Vop3OpClrexcp:          "v_clrexcp",
		Vop3OpMovreldB32:       "v_movreld_b32",
		Vop3OpMovrelsdB32:      "v_movrelsd_b32",
	},
	EncSMRD: {
		SmrdOpLoadDword:          "s_load_dword",
		SmrdOpLoadDwordx2:        "s_load_dwordx2",
		SmrdOpLoadDwordx4:        "s_load_dwordx4",
		SmrdOpLoadDwordx8:        "s_load_dwordx8",
		SmrdOpLoadDwordx16:       "s_load_dwordx16",
		SmrdOpBufferLoadDword:    "s_buffer_load_dword",
		SmrdOpBufferLoadDwordx2:  "s_buffer_load_dwordx2",
		SmrdOpBufferLoadDwordx4:  "s_buffer_load_dwordx4",
		SmrdOpBufferLoadDwordx8:  "s_buffer_load_dwordx8",
		SmrdOpBufferLoadDwordx16: "s_buffer_load_dwordx16",
		SmrdOpDcacheInvVol:       "s_dcache_inv_vol",
		SmrdOpMemtime:            "s_memtime",
		SmrdOpDcacheInv:          "s_dcache_inv",
	},
	EncMUBUF: {
		MubufOpLoadFormatX:      "buffer_load_format_x",
		MubufOpLoadFormatXy:     "buffer_load_format_xy",
		MubufOpLoadFormatXyz:    "buffer_load_format_xyz",
		MubufOpLoadFormatXyzw:   "buffer_load_format_xyzw",
		MubufOpStoreFormatX:     "buffer_store_format_x",
		MubufOpStoreFormatXy:    "buffer_store_format_xy",
		MubufOpStoreFormatXyz:   "buffer_store_format_xyz",
		MubufOpStoreFormatXyzw:  "buffer_store_format_xyzw",
		MubufOpLoadUbyte:        "buffer_load_ubyte",
		MubufOpLoadSbyte:        "buffer_load_sbyte",
		MubufOpLoadUshort:       "buffer_load_ushort",
		MubufOpLoadSshort:       "buffer_load_sshort",
		MubufOpLoadDword:        "buffer_load_dword",
		MubufOpLoadDwordx2:      "buffer_load_dwordx2",
		MubufOpLoadDwordx4:      "buffer_load_dwordx4",
		MubufOpLoadDwordx3:      "buffer_load_dwordx3",
		MubufOpStoreByte:        "buffer_store_byte",
		MubufOpStoreShort:       "buffer_store_short",
		MubufOpStoreDword:       "buffer_store_dword",
		MubufOpStoreDwordx2:     "buffer_store_dwordx2",
		MubufOpStoreDwordx4:     "buffer_store_dwordx4",
		MubufOpStoreDwordx3:     "buffer_store_dwordx3",
		MubufOpAtomicSwap:       "buffer_atomic_swap",
		MubufOpAtomicCmpswap:    "buffer_atomic_cmpswap",
		MubufOpAtomicAdd:        "buffer_atomic_add",
		MubufOpAtomicSub:        "buffer_atomic_sub",
		MubufOpAtomicSmin:       "buffer_atomic_smin",
		MubufOpAtomicUmin:       "buffer_atomic_umin",
		MubufOpAtomicSmax:       "buffer_atomic_smax",
		MubufOpAtomicUmax:       "buffer_atomic_umax",
		MubufOpAtomicAnd:        "buffer_atomic_and",
		MubufOpAtomicOr:         "buffer_atomic_or",
		MubufOpAtomicXor:        "buffer_atomic_xor",
		MubufOpAtomicInc:        "buffer_atomic_inc",
		MubufOpAtomicDec:        "buffer_atomic_dec",
		MubufOpAtomicFcmpswap:   "buffer_atomic_fcmpswap",
		MubufOpAtomicFmin:       "buffer_atomic_fmin",
		MubufOpAtomicFmax:       "buffer_atomic_fmax",
		MubufOpAtomicSwapX2:     "buffer_atomic_swap_x2",
		MubufOpAtomicCmpswapX2:  "buffer_atomic_cmpswap_x2",
		MubufOpAtomicAddX2:      "buffer_atomic_add_x2",
		MubufOpAtomicSubX2:      "buffer_atomic_sub_x2",
		MubufOpAtomicSminX2:     "buffer_atomic_smin_x2",
		MubufOpAtomicUminX2:     "buffer_atomic_umin_x2",
		MubufOpAtomicSmaxX2:     "buffer_atomic_smax_x2",
		MubufOpAtomicUmaxX2:     "buffer_atomic_umax_x2",
		MubufOpAtomicAndX2:      "buffer_atomic_and_x2",
		MubufOpAtomicOrX2:       "buffer_atomic_or_x2",
		MubufOpAtomicXorX2:      "buffer_atomic_xor_x2",
		MubufOpAtomicIncX2:      "buffer_atomic_inc_x2",
		MubufOpAtomicDecX2:      "buffer_atomic_dec_x2",
		MubufOpAtomicFcmpswapX2: "buffer_atomic_fcmpswap_x2",
		MubufOpAtomicFminX2:     "buffer_atomic_fmin_x2",
		MubufOpAtomicFmaxX2:     "buffer_atomic_fmax_x2",
		MubufOpWbinvl1Vol:       "buffer_wbinvl1_vol",
		MubufOpWbinvl1:          "buffer_wbinvl1",
	},
	EncDS: {
		DsOpAddU32:            "ds_add_u32",
		DsOpSubU32:            "ds_sub_u32",
		DsOpRsubU32:           "ds_rsub_u32",
		DsOpIncU32:            "ds_inc_u32",
		DsOpDecU32:            "ds_dec_u32",
		DsOpMinI32:            "ds_min_i32",
		DsOpMaxI32:            "ds_max_i32",
		DsOpMinU32:            "ds_min_u32",
		DsOpMaxU32:            "ds_max_u32",
		DsOpAndB32:            "ds_and_b32",
		DsOpOrB32:             "ds_or_b32",
		DsOpXorB32:            "ds_xor_b32",
		DsOpMskorB32:          "ds_mskor_b32",
		DsOpWriteB32:          "ds_write_b32",
		DsOpWrite2B32:         "ds_write2_b32",
		DsOpWrite2st64B32:     "ds_write2st64_b32",
		DsOpCmpstB32:          "ds_cmpst_b32",
		DsOpCmpstF32:          "ds_cmpst_f32",
		DsOpMinF32:            "ds_min_f32",
		DsOpMaxF32:            "ds_max_f32",
		DsOpNop:               "ds_nop",
		DsOpGwsSemaReleaseAll: "ds_gws_sema_release_all",
		DsOpGwsInit:           "ds_gws_init",
		DsOpGwsSemaV:          "ds_gws_sema_v",
		DsOpGwsSemaBr:         "ds_gws_sema_br",
		DsOpGwsSemaP:          "ds_gws_sema_p",
		DsOpGwsBarrier:        "ds_gws_barrier",
		DsOpWriteB8:           "ds_write_b8",
		DsOpWriteB16:          "ds_write_b16",
		DsOpAddRtnU32:         "ds_add_rtn_u32",
		DsOpSubRtnU32:         "ds_sub_rtn_u32",
		DsOpRsubRtnU32:        "ds_rsub_rtn_u32",
		DsOpIncRtnU32:         "ds_inc_rtn_u32",
		DsOpDecRtnU32:         "ds_dec_rtn_u32",
		DsOpMinRtnI32:         "ds_min_rtn_i32",
		DsOpMaxRtnI32:         "ds_max_rtn_i32",
		DsOpMinRtnU32:         "ds_min_rtn_u32",
		DsOpMaxRtnU32:         "ds_max_rtn_u32",
		DsOpAndRtnB32:         "ds_and_rtn_b32",
		DsOpOrRtnB32:          "ds_or_rtn_b32",
		DsOpXorRtnB32:         "ds_xor_rtn_b32",
		DsOpMskorRtnB32:       "ds_mskor_rtn_b32",
		DsOpWrxchgRtnB32:      "ds_wrxchg_rtn_b32",
		DsOpWrxchg2RtnB32:     "ds_wrxchg2_rtn_b32",
		DsOpWrxchg2st64RtnB32: "ds_wrxchg2st64_rtn_b32",
		DsOpCmpstRtnB32:       "ds_cmpst_rtn_b32",
		DsOpCmpstRtnF32:       "ds_cmpst_rtn_f32",
		DsOpMinRtnF32:         "ds_min_rtn_f32",
		DsOpMaxRtnF32:         "ds_max_rtn_f32",
		DsOpWrapRtnB32:        "ds_wrap_rtn_b32",
		DsOpSwizzleB32:        "ds_swizzle_b32",
		DsOpReadB32:           "ds_read_b32",
		DsOpRead2B32:          "ds_read2_b32",
		DsOpRead2st64B32:      "ds_read2st64_b32",
		DsOpReadI8:            "ds_read_i8",
		DsOpReadU8:            "ds_read_u8",
		DsOpReadI16:           "ds_read_i16",
		DsOpReadU16:           "ds_read_u16",
		DsOpConsume:           "ds_consume",
		DsOpAppend:            "ds_append",
		DsOpOrderedCount:      "ds_ordered_count",
		DsOpAddU64:            "ds_add_u64",
		DsOpSubU64:            "ds_sub_u64",
		DsOpRsubU64:           "ds_rsub_u64",
		DsOpIncU64:            "ds_inc_u64",
		DsOpDecU64:            "ds_dec_u64",
		DsOpMinI64:            "ds_min_i64",
		DsOpMaxI64:            "ds_max_i64",
		DsOpMinU64:            "ds_min_u64",
		DsOpMaxU64:            "ds_max_u64",
		DsOpAndB64:            "ds_and_b64",
		DsOpOrB64:             "ds_or_b64",
		DsOpXorB64:            "ds_xor_b64",
		DsOpMskorB64:          "ds_mskor_b64",
		DsOpWriteB64:          "ds_write_b64",
		DsOpWrite2B64:         "ds_write2_b64",
		DsOpWrite2st64B64:     "ds_write2st64_b64",
		DsOpCmpstB64:          "ds_cmpst_b64",
		DsOpCmpstF64:          "ds_cmpst_f64",
		DsOpMinF64:            "ds_min_f64",
		DsOpMaxF64:            "ds_max_f64",
		DsOpAddRtnU64:         "ds_add_rtn_u64",
		DsOpSubRtnU64:         "ds_sub_rtn_u64",
		DsOpRsubRtnU64:        "ds_rsub_rtn_u64",
		DsOpIncRtnU64:         "ds_inc_rtn_u64",
		DsOpDecRtnU64:         "ds_dec_rtn_u64",
		DsOpMinRtnI64:         "ds_min_rtn_i64",
		DsOpMaxRtnI64:         "ds_max_rtn_i64",
		DsOpMinRtnU64:         "ds_min_rtn_u64",
		DsOpMaxRtnU64:         "ds_max_rtn_u64",
		DsOpAndRtnB64:         "ds_and_rtn_b64",
		DsOpOrRtnB64:          "ds_or_rtn_b64",
		DsOpXorRtnB64:         "ds_xor_rtn_b64",
		DsOpMskorRtnB64:       "ds_mskor_rtn_b64",
		DsOpWrxchgRtnB64:      "ds_wrxchg_rtn_b64",
		DsOpWrxchg2RtnB64:     "ds_wrxchg2_rtn_b64",
		DsOpWrxchg2st64RtnB64: "ds_wrxchg2st64_rtn_b64",
		DsOpCmpstRtnB64:       "ds_cmpst_rtn_b64",
		DsOpCmpstRtnF64:       "ds_cmpst_rtn_f64",
		DsOpMinRtnF64:         "ds_min_rtn_f64",
		DsOpMaxRtnF64:         "ds_max_rtn_f64",
		DsOpReadB64:           "ds_read_b64",
		DsOpRead2B64:          "ds_read2_b64",
		DsOpRead2st64B64:      "ds_read2st64_b64",
		DsOpCondxchg32RtnB64:  "ds_condxchg32_rtn_b64",
		DsOpAddSrc2U32:        "ds_add_src2_u32",
		DsOpSubSrc2U32:        "ds_sub_src2_u32",
		DsOpRsubSrc2U32:       "ds_rsub_src2_u32",
		DsOpIncSrc2U32:        "ds_inc_src2_u32",
		DsOpDecSrc2U32:        "ds_dec_src2_u32",
		DsOpMinSrc2I32:        "ds_min_src2_i32",
		DsOpMaxSrc2I32:        "ds_max_src2_i32",
		DsOpMinSrc2U32:        "ds_min_src2_u32",
		DsOpMaxSrc2U32:        "ds_max_src2_u32",
		DsOpAndSrc2B32:        "ds_and_src2_b32",
		DsOpOrSrc2B32:         "ds_or_src2_b32",
		DsOpXorSrc2B32:        "ds_xor_src2_b32",
		DsOpWriteSrc2B32:      "ds_write_src2_b32",
		DsOpMinSrc2F32:        "ds_min_src2_f32",
		DsOpMaxSrc2F32:        "ds_max_src2_f32",
		DsOpAddSrc2U64:        "ds_add_src2_u64",
		DsOpSubSrc2U64:        "ds_sub_src2_u64",
		DsOpRsubSrc2U64:       "ds_rsub_src2_u64",
		DsOpIncSrc2U64:        "ds_inc_src2_u64",
		DsOpDecSrc2U64:        "ds_dec_src2_u64",
		DsOpMinSrc2I64:        "ds_min_src2_i64",
		DsOpMaxSrc2I64:        "ds_max_src2_i64",
		DsOpMinSrc2U64:        "ds_min_src2_u64",
		DsOpMaxSrc2U64:        "ds_max_src2_u64",
		DsOpAndSrc2B64:        "ds_and_src2_b64",
		DsOpOrSrc2B64:         "ds_or_src2_b64",
		DsOpXorSrc2B64:        "ds_xor_src2_b64",
		DsOpWriteSrc2B64:      "ds_write_src2_b64",
		DsOpMinSrc2F64:        "ds_min_src2_f64",
		DsOpMaxSrc2F64:        "ds_max_src2_f64",
		DsOpWriteB96:          "ds_write_b96",
		DsOpWriteB128:         "ds_write_b128",
		DsOpCondxchg32RtnB128: "ds_condxchg32_rtn_b128",
		DsOpReadB96:           "ds_read_b96",
		DsOpReadB128:          "ds_read_b128",
	},
	EncMIMG: {
		MimgOpLoad:           "image_load",
		MimgOpLoadMip:        "image_load_mip",
		MimgOpLoadPck:        "image_load_pck",
		MimgOpLoadPckSgn:     "image_load_pck_sgn",
		MimgOpLoadMipPck:     "image_load_mip_pck",
		MimgOpLoadMipPckSgn:  "image_load_mip_pck_sgn",
		MimgOpStore:          "image_store",
		MimgOpStoreMip:       "image_store_mip",
		MimgOpStorePck:       "image_store_pck",
		MimgOpStoreMipPck:    "image_store_mip_pck",
		MimgOpGetResinfo:     "image_get_resinfo",
		MimgOpAtomicSwap:     "image_atomic_swap",
		MimgOpAtomicCmpswap:  "image_atomic_cmpswap",
		MimgOpAtomicAdd:      "image_atomic_add",
		MimgOpAtomicSub:      "image_atomic_sub",
		MimgOpAtomicSmin:     "image_atomic_smin",
		MimgOpAtomicUmin:     "image_atomic_umin",
		MimgOpAtomicSmax:     "image_atomic_smax",
		MimgOpAtomicUmax:     "image_atomic_umax",
		MimgOpAtomicAnd:      "image_atomic_and",
		MimgOpAtomicOr:       "image_atomic_or",
		MimgOpAtomicXor:      "image_atomic_xor",
		MimgOpAtomicInc:      "image_atomic_inc",
		MimgOpAtomicDec:      "image_atomic_dec",
		MimgOpAtomicFcmpswap: "image_atomic_fcmpswap",
		MimgOpAtomicFmin:     "image_atomic_fmin",
		MimgOpAtomicFmax:     "image_atomic_fmax",
		MimgOpSample:         "image_sample",
		MimgOpSampleCl:       "image_sample_cl",
		MimgOpSampleD:        "image_sample_d",
		MimgOpSampleDCl:      "image_sample_d_cl",
		MimgOpSampleL:        "image_sample_l",
		MimgOpSampleB:        "image_sample_b",
		MimgOpSampleBCl:      "image_sample_b_cl",
		MimgOpSampleLz:       "image_sample_lz",
		MimgOpSampleC:        "image_sample_c",
		MimgOpSampleCCl:      "image_sample_c_cl",
		MimgOpSampleCD:       "image_sample_c_d",
		MimgOpSampleCDCl:     "image_sample_c_d_cl",
		MimgOpSampleCL:       "image_sample_c_l",
		MimgOpSampleCB:       "image_sample_c_b",
		MimgOpSampleCBCl:     "image_sample_c_b_cl",
		MimgOpSampleCLz:      "image_sample_c_lz",
		MimgOpSampleO:        "image_sample_o",
		MimgOpSampleClO:      "image_sample_cl_o",
		MimgOpSampleDO:       "image_sample_d_o",
		MimgOpSampleDClO:     "image_sample_d_cl_o",
		MimgOpSampleLO:       "image_sample_l_o",
		MimgOpSampleBO:       "image_sample_b_o",
		MimgOpSampleBClO:     "image_sample_b_cl_o",
		MimgOpSampleLzO:      "image_sample_lz_o",
		MimgOpSampleCO:       "image_sample_c_o",
		MimgOpSampleCClO:     "image_sample_c_cl_o",
		MimgOpSampleCDO:      "image_sample_c_d_o",
		MimgOpSampleCDClO:    "image_sample_c_d_cl_o",
		MimgOpSampleCLO:      "image_sample_c_l_o",
		MimgOpSampleCBO:      "image_sample_c_b_o",
		MimgOpSampleCBClO:    "image_sample_c_b_cl_o",
		MimgOpSampleCLzO:     "image_sample_c_lz_o",
		MimgOpGather4:        "image_gather4",
		MimgOpGather4Cl:      "image_gather4_cl",
		MimgOpGather4L:       "image_gather4_l",
		MimgOpGather4B:       "image_gather4_b",
		MimgOpGather4BCl:     "image_gather4_b_cl",
		MimgOpGather4Lz:      "image_gather4_lz",
		MimgOpGather4C:       "image_gather4_c",
		MimgOpGather4CCl:     "image_gather4_c_cl",
		MimgOpGather4CL:      "image_gather4_c_l",
		MimgOpGather4CB:      "image_gather4_c_b",
		MimgOpGather4CBCl:    "image_gather4_c_b_cl",
		MimgOpGather4CLz:     "image_gather4_c_lz",
		MimgOpGather4O:       "image_gather4_o",
		MimgOpGather4ClO:     "image_gather4_cl_o",
		MimgOpGather4LO:      "image_gather4_l_o",
		MimgOpGather4BO:      "image_gather4_b_o",
		MimgOpGather4BClO:    "image_gather4_b_cl_o",
		MimgOpGather4LzO:     "image_gather4_lz_o",
		MimgOpGather4CO:      "image_gather4_c_o",
		MimgOpGather4CClO:    "image_gather4_c_cl_o",
		MimgOpGather4CLO:     "image_gather4_c_l_o",
		MimgOpGather4CBO:     "image_gather4_c_b_o",
		MimgOpGather4CBClO:   "image_gather4_c_b_cl_o",
		MimgOpGather4CLzO:    "image_gather4_c_lz_o",
		MimgOpGetLod:         "image_get_lod",
		MimgOpSampleCd:       "image_sample_cd",
		MimgOpSampleCdCl:     "image_sample_cd_cl",
		MimgOpSampleCCd:      "image_sample_c_cd",
		MimgOpSampleCCdCl:    "image_sample_c_cd_cl",
		MimgOpSampleCdO:      "image_sample_cd_o",
		MimgOpSampleCdClO:    "image_sample_cd_cl_o",
		MimgOpSampleCCdO:     "image_sample_c_cd_o",
		MimgOpSampleCCdClO:   "image_sample_c_cd_cl_o",
	},
	EncEXP: {},
}

func (instr *Instruction) GetMnemotic() string {
	var b string
	switch instr.Encoding {
	case EncSOP2, EncSOPK, EncSOP1, EncSOPC, EncSOPP:
		b = Mnemotics[instr.Encoding][instr.Details.(*ScalarDetails).Op]
	case EncVOP2, EncVOP1, EncVOPC:
		b = Mnemotics[instr.Encoding][instr.Details.(*VectorDetails).Op]
	case EncVOP3:
		if instr.Details.(*Vop3Details).Op < 0x100 {
			b = Mnemotics[EncVOPC][instr.Details.(*Vop3Details).Op]
		} else {
			b = Mnemotics[instr.Encoding][instr.Details.(*Vop3Details).Op]
		}
	case EncVINTRP:
	case EncSMRD:
		b = Mnemotics[instr.Encoding][instr.Details.(*SmrdDetails).Op]
	case EncMTBUF, EncMUBUF:
		b = Mnemotics[instr.Encoding][instr.Details.(*MubufDetails).Op]
	case EncMIMG:
		b = Mnemotics[instr.Encoding][instr.Details.(*MimgDetails).Op]
	case EncDS:
	case EncEXP:
		b = "export"
	}
	if len(b) == 0 {
		return "??"
	}

	return b
}

func (instr *Instruction) GetFieldsString() string {
	var b strings.Builder
	switch instr.Encoding {
	case EncSOP2:
		fmt.Fprintf(&b, "sdst=%s ssrc1=%s ssrc0=%s",
			OperandToString(instr.Details.(*ScalarDetails).Dst),
			OperandToString(instr.Details.(*ScalarDetails).Src1),
			OperandToString(instr.Details.(*ScalarDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncSOPK:
		fmt.Fprintf(&b, "sdst=%s simm=0x%04X",
			OperandToString(instr.Details.(*ScalarDetails).Dst),
			instr.Details.(*ScalarDetails).Imm16,
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncSOP1:
		fmt.Fprintf(&b, "sdst=%s ssrc0=%s",
			OperandToString(instr.Details.(*ScalarDetails).Dst),
			OperandToString(instr.Details.(*ScalarDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncSOPC:
		fmt.Fprintf(&b, "ssrc1=%s ssrc0=%s",
			OperandToString(instr.Details.(*ScalarDetails).Src1),
			OperandToString(instr.Details.(*ScalarDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncSOPP:
		fmt.Fprintf(&b, "simm=0x%04X",
			instr.Details.(*ScalarDetails).Imm16,
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncVOP2:
		fmt.Fprintf(&b, "vdst=%d vsrc1=%d src0=%s",
			instr.Details.(*VectorDetails).Dst,
			instr.Details.(*VectorDetails).Src1,
			OperandToString(instr.Details.(*VectorDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncVOP1:
		fmt.Fprintf(&b, "vdst=%d src0=%s",
			instr.Details.(*VectorDetails).Dst,
			OperandToString(instr.Details.(*VectorDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncVOPC:
		fmt.Fprintf(&b, "vsrc1=%d src0=%s",
			instr.Details.(*VectorDetails).Src1,
			OperandToString(instr.Details.(*VectorDetails).Src0),
		)
		if instr.HasLiteral {
			fmt.Fprintf(&b, " lit=0x%08X", instr.Literal)
		}
	case EncVINTRP:
	case EncVOP3:
		fmt.Fprintf(&b, "neg=%d omod=%d src2=%s src1=%s src0=%s clamp=%d abs=%d sdst=%s vdst=%s",
			instr.Details.(*Vop3Details).Neg,
			instr.Details.(*Vop3Details).OMod,
			OperandToString(instr.Details.(*Vop3Details).Src2),
			OperandToString(instr.Details.(*Vop3Details).Src1),
			OperandToString(instr.Details.(*Vop3Details).Src0),
			nstd.Btoi(instr.Details.(*Vop3Details).Clamp),
			instr.Details.(*Vop3Details).Abs,
			OperandToString(instr.Details.(*Vop3Details).Sdst),
			OperandToString(instr.Details.(*Vop3Details).Dst),
		)
	case EncSMRD:
		fmt.Fprintf(&b, "sdst=%d sbase=%d imm=%d offset=%d",
			instr.Details.(*SmrdDetails).Dst,
			instr.Details.(*SmrdDetails).Base,
			nstd.Btoi(instr.Details.(*SmrdDetails).ImmOff),
			instr.Details.(*SmrdDetails).Offset,
		)
	case EncMTBUF:
	case EncMUBUF:
		fmt.Fprintf(&b, "offset=%d offen=%d idxen=%d glc=%d addr64=%d lds=%d vaddr=%d vdata=%d srsrc=%d slc=%d tfe=%d soffset=%d",
			instr.Details.(*MubufDetails).Offset,
			nstd.Btoi(instr.Details.(*MubufDetails).Offen),
			nstd.Btoi(instr.Details.(*MubufDetails).Idxen),
			nstd.Btoi(instr.Details.(*MubufDetails).Glc),
			nstd.Btoi(instr.Details.(*MubufDetails).Addr64),
			nstd.Btoi(instr.Details.(*MubufDetails).Lds),
			instr.Details.(*MubufDetails).Vaddr,
			instr.Details.(*MubufDetails).Vdata,
			instr.Details.(*MubufDetails).Srsrc,
			nstd.Btoi(instr.Details.(*MubufDetails).Slc),
			nstd.Btoi(instr.Details.(*MubufDetails).Tfe),
			instr.Details.(*MubufDetails).Soffset,
		)
	case EncMIMG:
		fmt.Fprintf(&b, "ssamp=%d srsrc=%d vdata=%d vaddr=%d slc=%d lwe=%d tfe=%d r128=%d da=%d glc=%d unrm=%d dmask=%d",
			instr.Details.(*MimgDetails).Ssamp,
			instr.Details.(*MimgDetails).Srsrc,
			instr.Details.(*MimgDetails).Vdata,
			instr.Details.(*MimgDetails).Vaddr,
			nstd.Btoi(instr.Details.(*MimgDetails).Slc),
			nstd.Btoi(instr.Details.(*MimgDetails).Lwe),
			nstd.Btoi(instr.Details.(*MimgDetails).Tfe),
			nstd.Btoi(instr.Details.(*MimgDetails).R128),
			nstd.Btoi(instr.Details.(*MimgDetails).Da),
			nstd.Btoi(instr.Details.(*MimgDetails).Glc),
			nstd.Btoi(instr.Details.(*MimgDetails).Unorm),
			instr.Details.(*MimgDetails).Dmask,
		)
	case EncDS:
	case EncEXP:
		fmt.Fprintf(&b, "vsrc3=%d vsrc2=%d vsrc1=%d vsrc0=%d vm=%d done=%d compr=%d target=%d en=%d",
			instr.Details.(*ExpDetails).VSrcs[3],
			instr.Details.(*ExpDetails).VSrcs[2],
			instr.Details.(*ExpDetails).VSrcs[1],
			instr.Details.(*ExpDetails).VSrcs[0],
			nstd.Btoi(instr.Details.(*ExpDetails).Vm),
			nstd.Btoi(instr.Details.(*ExpDetails).Done),
			nstd.Btoi(instr.Details.(*ExpDetails).Compr),
			instr.Details.(*ExpDetails).Target,
			instr.Details.(*ExpDetails).En,
		)
	}
	if b.Len() == 0 {
		return "??"
	}

	return b.String()
}

// Based on 5.2 Scalar ALU Operands.
func OperandToString(op uint32) string {
	switch {
	case op >= OpSgpr0 && op <= OpSgpr103:
		return fmt.Sprintf("s%d", op)
	case op == OpFlatScratchLo:
		return "flat_scratch_lo"
	case op == OpFlatScratchHi:
		return "flat_scratch_hi"
	case op == OpVccLo:
		return "vcc_lo"
	case op == OpVccHi:
		return "vcc_hi"
	case op == OpTbaLo:
		return "tba_lo"
	case op == OpTbaHi:
		return "tba_hi"
	case op == OpTmaLo:
		return "tma_lo"
	case op == OpTmaHi:
		return "tma_hi"
	case op >= OpTtmp0 && op <= OpTtmp11:
		return fmt.Sprintf("ttmp%d", op-OpTtmp0)
	case op == OpM0:
		return "m0"
	case op == OpExecLo:
		return "exec_lo"
	case op == OpExecHi:
		return "exec_hi"
	case op == OpInt0:
		return "0"
	case op >= OpPosInt1 && op <= OpPosInt64:
		return fmt.Sprint(op - OpInt0)
	case op >= OpNegInt1 && op <= OpNegInt16:
		return fmt.Sprintf("-%d", op-(OpNegInt1-1))
	case op == OpFloat05:
		return "0.5"
	case op == OpFloatNeg05:
		return "-0.5"
	case op == OpFloat10:
		return "1.0"
	case op == OpFloatNeg10:
		return "-1.0"
	case op == OpFloat20:
		return "2.0"
	case op == OpFloatNeg20:
		return "-2.0"
	case op == OpFloat40:
		return "4.0"
	case op == OpFloatNeg40:
		return "-4.0"
	case op == OpVccz:
		return "vccz"
	case op == OpExecz:
		return "execz"
	case op == OpScc:
		return "scc"
	case op == OpLiteral:
		return "lit"
	case op >= OpVgpr0 && op <= OpVgpr255:
		return fmt.Sprintf("v%d", op-OpVgpr0)
	}

	return fmt.Sprintf("?? (%d)", op)
}
