package common

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	hsp "github.com/CovenantSQL/HashStablePack/marshalhash"
)

// MarshalHash marshals for hash
func (z *SpirvComputeShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 4
	o = append(o, 0x84)
	o = hsp.AppendArrayHeader(o, uint32(len(z.MubufFormats)))
	for za0001 := range z.MubufFormats {
		// map header, size 3
		o = append(o, 0x83)
		o = hsp.AppendUint32(o, z.MubufFormats[za0001].PC)
		o = hsp.AppendUint8(o, z.MubufFormats[za0001].DataFormat)
		o = hsp.AppendUint8(o, z.MubufFormats[za0001].NumFormat)
	}
	o = hsp.AppendUint32(o, z.ThreadX)
	o = hsp.AppendUint32(o, z.ThreadY)
	o = hsp.AppendUint32(o, z.ThreadZ)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvComputeShaderContext) Msgsize() (s int) {
	s = 1 + 13 + hsp.ArrayHeaderSize + (len(z.MubufFormats) * (25 + hsp.Uint32Size + hsp.Uint8Size + hsp.Uint8Size)) + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *SpirvFragmentShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 7
	o = append(o, 0x87)
	o = hsp.AppendBool(o, z.DepthBeforeShader)
	o = hsp.AppendBool(o, z.FrontFaceEnable)
	o = hsp.AppendArrayHeader(o, uint32(len(z.MubufFormats)))
	for za0002 := range z.MubufFormats {
		// map header, size 3
		o = append(o, 0x83)
		o = hsp.AppendUint32(o, z.MubufFormats[za0002].PC)
		o = hsp.AppendUint8(o, z.MubufFormats[za0002].DataFormat)
		o = hsp.AppendUint8(o, z.MubufFormats[za0002].NumFormat)
	}
	o = hsp.AppendUint32(o, z.PsInControl)
	o = hsp.AppendUint32(o, z.PsInputAddress)
	o = hsp.AppendArrayHeader(o, uint32(32))
	for za0001 := range z.PsInputControls {
		o = hsp.AppendUint32(o, z.PsInputControls[za0001])
	}
	o = hsp.AppendUint32(o, z.ZOrder)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvFragmentShaderContext) Msgsize() (s int) {
	s = 1 + 18 + hsp.BoolSize + 16 + hsp.BoolSize + 13 + hsp.ArrayHeaderSize + (len(z.MubufFormats) * (25 + hsp.Uint32Size + hsp.Uint8Size + hsp.Uint8Size)) + 12 + hsp.Uint32Size + 15 + hsp.Uint32Size + 16 + hsp.ArrayHeaderSize + (int(32) * (hsp.Uint32Size)) + 7 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z SpirvMubufFormat) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint8(o, z.DataFormat)
	o = hsp.AppendUint8(o, z.NumFormat)
	o = hsp.AppendUint32(o, z.PC)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SpirvMubufFormat) Msgsize() (s int) {
	s = 1 + 11 + hsp.Uint8Size + 10 + hsp.Uint8Size + 3 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *SpirvShaderKey) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 2
	o = append(o, 0x82)
	o = hsp.AppendUint64(o, uint64(z.Address))
	o = hsp.AppendUint64(o, z.ContextHash)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvShaderKey) Msgsize() (s int) {
	s = 1 + hsp.Uint64Size + 12 + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *SpirvVertexShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 5
	o = append(o, 0x85)
	o = hsp.AppendUint8(o, z.ClipDistEnable)
	o = hsp.AppendUint8(o, z.CullDistEnable)
	o = hsp.AppendUint64(o, uint64(z.FetchShaderAddress))
	o = hsp.AppendArrayHeader(o, uint32(len(z.MubufFormats)))
	for za0001 := range z.MubufFormats {
		// map header, size 3
		o = append(o, 0x83)
		o = hsp.AppendUint32(o, z.MubufFormats[za0001].PC)
		o = hsp.AppendUint8(o, z.MubufFormats[za0001].DataFormat)
		o = hsp.AppendUint8(o, z.MubufFormats[za0001].NumFormat)
	}
	o = hsp.AppendUint32(o, z.VsExportCount)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvVertexShaderContext) Msgsize() (s int) {
	s = 1 + 15 + hsp.Uint8Size + 15 + hsp.Uint8Size + hsp.Uint64Size + 13 + hsp.ArrayHeaderSize + (len(z.MubufFormats) * (25 + hsp.Uint32Size + hsp.Uint8Size + hsp.Uint8Size)) + 14 + hsp.Uint32Size
	return
}
