package common

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	hsp "github.com/CovenantSQL/HashStablePack/marshalhash"
)

// MarshalHash marshals for hash
func (z SpirvComputeShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint32(o, z.ThreadX)
	o = hsp.AppendUint32(o, z.ThreadY)
	o = hsp.AppendUint32(o, z.ThreadZ)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SpirvComputeShaderContext) Msgsize() (s int) {
	s = 1 + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *SpirvFragmentShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 6
	o = append(o, 0x86)
	o = hsp.AppendBool(o, z.DepthBeforeShader)
	o = hsp.AppendBool(o, z.FrontFaceEnable)
	o = hsp.AppendUint32(o, z.PsInControl)
	o = hsp.AppendUint32(o, z.PsInputAddress)
	o = hsp.AppendArrayHeader(o, uint32(32))
	for za0001 := range z.PsInputControls {
		o = hsp.AppendUint32(o, z.PsInputControls[za0001])
	}
	o = hsp.AppendUint32(o, z.ZOrder)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvFragmentShaderContext) Msgsize() (s int) {
	s = 1 + 18 + hsp.BoolSize + 16 + hsp.BoolSize + 12 + hsp.Uint32Size + 15 + hsp.Uint32Size + 16 + hsp.ArrayHeaderSize + (int(32) * (hsp.Uint32Size)) + 7 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *SpirvVertexShaderContext) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint8(o, z.ClipDistEnable)
	o = hsp.AppendUint8(o, z.CullDistEnable)
	o = hsp.AppendUint64(o, uint64(z.FetchShaderAddress))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SpirvVertexShaderContext) Msgsize() (s int) {
	s = 1 + 15 + hsp.Uint8Size + 15 + hsp.Uint8Size + hsp.Uint64Size
	return
}
