package structs

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	hsp "github.com/CovenantSQL/HashStablePack/marshalhash"
)

// MarshalHash marshals for hash
func (z *BufferDescriptor) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 19
	o = append(o, 0xde, 0x0, 0x13)
	o = hsp.AppendBool(o, z.AddTidEnable)
	o = hsp.AppendBool(o, z.Atc)
	o = hsp.AppendUint64(o, uint64(z.BaseAddress))
	o = hsp.AppendUint8(o, z.DataFormat)
	o = hsp.AppendUint8(o, z.DstSelW)
	o = hsp.AppendUint8(o, z.DstSelX)
	o = hsp.AppendUint8(o, z.DstSelY)
	o = hsp.AppendUint8(o, z.DstSelZ)
	o = hsp.AppendUint8(o, z.ElementSize)
	o = hsp.AppendBool(o, z.HashEnable)
	o = hsp.AppendBool(o, z.Heap)
	o = hsp.AppendUint8(o, z.IndexStride)
	o = hsp.AppendUint8(o, z.MType)
	o = hsp.AppendUint8(o, z.NumFormat)
	o = hsp.AppendUint32(o, z.NumRecords)
	o = hsp.AppendUint16(o, z.Stride)
	o = hsp.AppendBool(o, z.SwizzleCache)
	o = hsp.AppendBool(o, z.SwizzleEnable)
	o = hsp.AppendUint8(o, z.Type)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BufferDescriptor) Msgsize() (s int) {
	s = 3 + 13 + hsp.BoolSize + 4 + hsp.BoolSize + hsp.Uint64Size + 11 + hsp.Uint8Size + 8 + hsp.Uint8Size + 8 + hsp.Uint8Size + 8 + hsp.Uint8Size + 8 + hsp.Uint8Size + 12 + hsp.Uint8Size + 11 + hsp.BoolSize + 5 + hsp.BoolSize + 12 + hsp.Uint8Size + 6 + hsp.Uint8Size + 10 + hsp.Uint8Size + 11 + hsp.Uint32Size + 7 + hsp.Uint16Size + 13 + hsp.BoolSize + 14 + hsp.BoolSize + 5 + hsp.Uint8Size
	return
}
