// Code generated by stub_gen.go; DO NOT EDIT.

package elf

import (
	"unsafe"

	"github.com/LamkasDev/sharkie/cmd/asm"
	. "github.com/LamkasDev/sharkie/cmd/structs"
	"github.com/LamkasDev/sharkie/cmd/structs/fs"
)

func CreateDispatcher(goFn any) asm.StubDispatcher {
	switch fn := goFn.(type) {
	case func() int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn())
		}
	case func() int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn())
		}
	case func() uint64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn())
		}
	case func() uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn())
		}
	case func(uint32) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI)))
		}
	case func(uintptr) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI))
		}
	case func(uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI))
		}
	case func(fs.FileDescriptor) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI)))
		}
	case func(fs.FileDescriptor) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI)))
		}
	case func(uintptr, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, Cstring(ctx.SI)))
		}
	case func(uint32, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), ctx.SI))
		}
	case func(int32, uintptr) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(int32(ctx.DI), ctx.SI))
		}
	case func(uint32, uint32) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), uint32(ctx.SI)))
		}
	case func(uint32, uintptr) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), ctx.SI))
		}
	case func(Cstring, int64) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(Cstring(ctx.DI), int64(ctx.SI)))
		}
	case func(Cstring, uintptr) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(Cstring(ctx.DI), ctx.SI))
		}
	case func(fs.FileDescriptor, int64) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), int64(ctx.SI)))
		}
	case func(fs.FileDescriptor, uintptr) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), ctx.SI))
		}
	case func(uintptr, uint64) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI)))
		}
	case func(uintptr, int32) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, int32(ctx.SI)))
		}
	case func(uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI))
		}
	case func(uint32, uint32, uintptr) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), uint32(ctx.SI), ctx.DX))
		}
	case func(uintptr, uintptr, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, Cstring(ctx.DX)))
		}
	case func(Cstring, FileFlags, FileMode) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(Cstring(ctx.DI), FileFlags(ctx.SI), FileMode(ctx.DX)))
		}
	case func(uintptr, uint64, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), Cstring(ctx.DX)))
		}
	case func(uintptr, uint64, int32) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX)))
		}
	case func(uintptr, int32, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, int32(ctx.SI), ctx.DX))
		}
	case func(uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX))
		}
	case func(fs.FileDescriptor, uintptr, uint64, int64) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), ctx.SI, uint64(ctx.DX), int64(ctx.CX)))
		}
	case func(fs.FileDescriptor, uint64, uintptr) int32:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), uint64(ctx.SI), ctx.DX))
		}
	case func(fs.FileDescriptor, uintptr, uint64) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), ctx.SI, uint64(ctx.DX)))
		}
	case func(fs.FileDescriptor, int64, int32) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), int64(ctx.SI), int32(ctx.DX)))
		}
	case func(fs.FileDescriptor, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(fs.FileDescriptor(ctx.DI), ctx.SI, ctx.DX, ctx.CX))
		}
	case func(Cstring, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(Cstring(ctx.DI), ctx.SI, ctx.DX, ctx.CX))
		}
	case func(uintptr, uint64, int32, int32) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX)))
		}
	case func(uintptr, uint64, uint32, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), uint32(ctx.DX), ctx.CX))
		}
	case func(uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX))
		}
	case func(uint32, uintptr, uintptr, uintptr, uintptr) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), ctx.SI, ctx.DX, ctx.CX, ctx.R8))
		}
	case func(uintptr, uintptr, uintptr, uintptr, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, Cstring(ctx.R8)))
		}
	case func(uintptr, Cstring, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, Cstring(ctx.SI), ctx.DX, ctx.CX, ctx.R8))
		}
	case func(uintptr, uint64, int32, int32, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX), Cstring(ctx.R8)))
		}
	case func(uintptr, uint64, uint32, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), uint32(ctx.DX), ctx.CX, ctx.R8))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8))
		}
	case func(uint32, uint32, uintptr, uintptr, uintptr, uintptr) int64:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(uint32(ctx.DI), uint32(ctx.SI), ctx.DX, ctx.CX, ctx.R8, ctx.R9))
		}
	case func(Cstring, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(Cstring(ctx.DI), ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9))
		}
	case func(uintptr, Cstring, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, Cstring(ctx.SI), ctx.DX, ctx.CX, ctx.R8, ctx.R9))
		}
	case func(uintptr, uint64, int32, int32, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX), ctx.R8, ctx.R9))
		}
	case func(uintptr, uint64, int32, int32, fs.FileDescriptor, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX), fs.FileDescriptor(ctx.R8), ctx.R9))
		}
	case func(uintptr, uintptr, uint64, uint64, int32, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, uint64(ctx.DX), uint64(ctx.CX), int32(ctx.R8), ctx.R9))
		}
	case func(uintptr, Cstring, uint32, int32, int32, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, Cstring(ctx.SI), uint32(ctx.DX), int32(ctx.CX), int32(ctx.R8), ctx.R9))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*Cstring)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7))
		}
	case func(uintptr, uint64, int32, int32, fs.FileDescriptor, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX), fs.FileDescriptor(ctx.R8), ctx.R9, arg7))
		}
	case func(uintptr, uint64, int32, int32, uintptr, uintptr, Cstring) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*Cstring)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			return uintptr(fn(ctx.DI, uint64(ctx.SI), int32(ctx.DX), int32(ctx.CX), ctx.R8, ctx.R9, arg7))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7, arg8))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, Cstring, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*Cstring)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			arg9 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+24))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7, arg8, arg9))
		}
	case func(uint32, uintptr, uintptr, uintptr, uintptr, uint32, uint32, uint32, int64) int64:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uint32)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*uint32)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			arg9 := *(*int64)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+24))
			return uintptr(fn(uint32(ctx.DI), ctx.SI, ctx.DX, ctx.CX, ctx.R8, uint32(ctx.R9), arg7, arg8, arg9))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			arg9 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+24))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7, arg8, arg9))
		}
	case func(uint32, uint32, uintptr, uintptr, uintptr, uintptr, uint32, uint32, uint32, int64) int64:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uint32)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*uint32)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			arg9 := *(*uint32)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+24))
			arg10 := *(*int64)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+32))
			return uintptr(fn(uint32(ctx.DI), uint32(ctx.SI), ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7, arg8, arg9, arg10))
		}
	case func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		return func(ctx *asm.RegContext) uintptr {
			arg7 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+8))
			arg8 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+16))
			arg9 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+24))
			arg10 := *(*uintptr)(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+32))
			return uintptr(fn(ctx.DI, ctx.SI, ctx.DX, ctx.CX, ctx.R8, ctx.R9, arg7, arg8, arg9, arg10))
		}
	default:
		panic("unsupported function type")
	}
}
