package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/LamkasDev/sharkie/cmd/structs/gcn"
)

type GcnRegister struct {
	OriginalName string
	GoName       string
}

func main() {
	input, err := os.ReadFile(path.Join("..", "gcn_gen", "si_ci_vi_merged_offset.h"))
	if err != nil {
		panic(err)
	}
	re := regexp.MustCompile(`constexpr\s+unsigned\s+int\s+([a-z]+)([A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|[0-9]+);`)

	banks := make(map[string]map[uint32][]GcnRegister)
	scanner := bufio.NewScanner(bytes.NewReader(input))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		matches := re.FindStringSubmatch(line)
		if len(matches) == 4 {
			prefix := matches[1]
			name := matches[2]
			valStr := matches[3]

			// Parse the hex value.
			valStr = strings.TrimPrefix(valStr, "0x")
			valUint, err := strconv.ParseUint(valStr, 16, 32)
			if err != nil {
				continue
			}

			// Apply decrement logic to find the bank and relative offset.
			var bankName string
			var offset uint32
			switch {
			case valUint >= gcn.GcnRegBaseUserConfig:
				bankName = "UserConfig"
				offset = uint32(valUint) - gcn.GcnRegBaseUserConfig
			case valUint >= gcn.GcnRegBaseContext:
				bankName = "Context"
				offset = uint32(valUint) - gcn.GcnRegBaseContext
			case valUint >= gcn.GcnRegBaseShader:
				bankName = "Shader"
				offset = uint32(valUint) - gcn.GcnRegBaseShader
			case valUint >= gcn.GcnRegBaseConfig:
				bankName = "Config"
				offset = uint32(valUint) - gcn.GcnRegBaseConfig
			default:
				bankName = "System"
				offset = uint32(valUint)
			}

			if offset < gcn.GcnRegBankSize {
				if banks[bankName] == nil {
					banks[bankName] = make(map[uint32][]GcnRegister)
				}
				banks[bankName][offset] = append(banks[bankName][offset], GcnRegister{
					OriginalName: name,
					GoName:       fmt.Sprintf("GREG_%s_%s", strings.ToUpper(prefix), name),
				})
			}
		}
	}

	generateGoCode(banks, path.Join("..", "gcn", "gcn_registers.go"))
}

func generateGoCode(banks map[string]map[uint32][]GcnRegister, fileName string) {
	file, err := os.Create(fileName)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	fmt.Fprintln(file, "// Code generated by gcn_gen.go; DO NOT EDIT.")
	fmt.Fprintln(file, "package gcn\n")

	bankNames := []string{"Config", "Shader", "Context", "UserConfig"}
	for _, bankName := range bankNames {
		offsets, ok := banks[bankName]
		if !ok {
			continue
		}

		// Sort offsets so the file is readable.
		var sortedOffsets []int
		for k := range offsets {
			sortedOffsets = append(sortedOffsets, int(k))
		}
		sort.Ints(sortedOffsets)

		// Output all constants.
		fmt.Fprintf(file, "// %s registers.\nconst (\n", bankName)
		for _, off := range sortedOffsets {
			for _, entry := range offsets[uint32(off)] {
				fmt.Fprintf(file, "\t%s = 0x%04X\n", entry.GoName, off)
			}
		}
		fmt.Fprintln(file, ")\n")

		// Output de-duplicated map.
		fmt.Fprintf(file, "var %sRegisterNames = map[uint32]string{\n", bankName)
		for _, offset := range sortedOffsets {
			var names []string
			for _, register := range offsets[uint32(offset)] {
				names = append(names, register.OriginalName)
			}
			fmt.Fprintf(file, "\t0x%04X: \"%s\",\n", offset, strings.Join(unique(names), " / "))
		}
		fmt.Fprintln(file, "}\n")
	}
}

func unique(strSlice []string) []string {
	keys := make(map[string]bool)
	var list []string
	for _, entry := range strSlice {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}

	return list
}
