package dce

const (
	SCE_DCE_REFRESH_RATE_UNKNOWN  = 0
	SCE_DCE_REFRESH_RATE_23_98HZ  = 1
	SCE_DCE_REFRESH_RATE_50HZ     = 2
	SCE_DCE_REFRESH_RATE_59_94HZ  = 3
	SCE_DCE_REFRESH_RATE_119_88HZ = 13
	SCE_DCE_REFRESH_RATE_89_91HZ  = 35
	SCE_DCE_REFRESH_RATE_ANY      = 0xFFFFFFFFFFFFFFFF
)
