package gpu

// TODO: write a generator from si_ci_vi_merged_offset.h, otherwise it'll take forever.
// Shader register offsets (DWORD offset from context space base 0x2C00).
const (
	// Pixel shader program.
	REG_PS_SHADER_PROGRAM_LO    = 0x008
	REG_PS_SHADER_PROGRAM_HI    = 0x009
	REG_PS_SHADER_PROGRAM_RSRC1 = 0x00A
	REG_PS_SHADER_PROGRAM_RSRC2 = 0x00B

	// Vertex shader program.
	REG_VS_SHADER_PROGRAM_LO    = 0x048
	REG_VS_SHADER_PROGRAM_HI    = 0x049
	REG_VS_SHADER_PROGRAM_RSRC1 = 0x04A
	REG_VS_SHADER_PROGRAM_RSRC2 = 0x04B
)

var ShaderRegisterNames = map[uint32]string{
	// Pixel shader program.
	REG_PS_SHADER_PROGRAM_LO:    "REG_PS_SHADER_PROGRAM_LO",
	REG_PS_SHADER_PROGRAM_HI:    "REG_PS_SHADER_PROGRAM_HI",
	REG_PS_SHADER_PROGRAM_RSRC1: "REG_PS_SHADER_PROGRAM_RSRC1",
	REG_PS_SHADER_PROGRAM_RSRC2: "REG_PS_SHADER_PROGRAM_RSRC2",

	// Vertex shader program.
	REG_VS_SHADER_PROGRAM_LO:    "REG_VS_SHADER_PROGRAM_LO",
	REG_VS_SHADER_PROGRAM_HI:    "REG_VS_SHADER_PROGRAM_HI",
	REG_VS_SHADER_PROGRAM_RSRC1: "REG_VS_SHADER_PROGRAM_RSRC1",
	REG_VS_SHADER_PROGRAM_RSRC2: "REG_VS_SHADER_PROGRAM_RSRC2",
}
