package gpu

import "fmt"

// TODO: write a generator from si_ci_vi_merged_offset.h, otherwise it'll take forever.
// Context register offsets (DWORD offset from context space base 0xA000).
const (
	// Depth buffer.
	REG_DB_RENDER_CONTROL     = 0x0000
	REG_DB_COUNT_CONTROL      = 0x0001
	REG_DB_DEPTH_VIEW         = 0x0002
	REG_DB_RENDER_OVERRIDE    = 0x0003
	REG_DB_RENDER_OVERRIDE2   = 0x0004
	REG_DB_HTILE_DATA_BASE    = 0x0005
	REG_DB_DEPTH_BOUNDS_MIN   = 0x0008
	REG_DB_DEPTH_BOUNDS_MAX   = 0x0009
	REG_DB_STENCIL_CLEAR      = 0x000A
	REG_DB_DEPTH_CLEAR        = 0x000B
	REG_DB_DEPTH_INFO         = 0x000F
	REG_DB_Z_INFO             = 0x0010
	REG_DB_STENCIL_INFO       = 0x0011
	REG_DB_Z_READ_BASE        = 0x0012
	REG_DB_STENCIL_READ_BASE  = 0x0013
	REG_DB_Z_WRITE_BASE       = 0x0014
	REG_DB_STENCIL_WRITE_BASE = 0x0015
	REG_DB_DEPTH_SIZE         = 0x0016
	REG_DB_DEPTH_SLICE        = 0x0017

	REG_DB_STENCIL_CONTROL   = 0x010B
	REG_DB_STENCILREFMASK    = 0x010C
	REG_DB_STENCILREFMASK_BF = 0x010D

	REG_DB_DEPTH_CONTROL        = 0x0200
	REG_DB_EQAA                 = 0x0201
	REG_DB_SHADER_CONTROL       = 0x0203
	REG_DB_HTILE_SURFACE        = 0x02AF
	REG_DB_SRESULTS_COMP_STATE0 = 0x02B0
	REG_DB_SRESULTS_COMP_STATE1 = 0x02B1
	REG_DB_PRELOAD_CONTROL      = 0x02B2
	REG_DB_ALPHA_TO_MASK        = 0x02DC

	// Color buffer slots 0–7.
	REG_CB_COLOR0_BASE        = 0x0318
	REG_CB_COLOR0_PITCH       = 0x0319
	REG_CB_COLOR0_SLICE       = 0x031A
	REG_CB_COLOR0_VIEW        = 0x031B
	REG_CB_COLOR0_INFO        = 0x031C
	REG_CB_COLOR0_ATTRIB      = 0x031D
	REG_CB_COLOR0_CMASK       = 0x031F
	REG_CB_COLOR0_CMASK_SLICE = 0x0320
	REG_CB_COLOR0_FMASK       = 0x0321
	REG_CB_COLOR0_FMASK_SLICE = 0x0322
	REG_CB_COLOR0_CLEAR_WORD0 = 0x0323
	REG_CB_COLOR0_CLEAR_WORD1 = 0x0324

	REG_CB_COLOR_STRIDE = 0xF
)

var ContextRegisterNames = map[uint32]string{
	REG_DB_RENDER_CONTROL:     "REG_DB_RENDER_CONTROL",
	REG_DB_COUNT_CONTROL:      "REG_DB_COUNT_CONTROL",
	REG_DB_DEPTH_VIEW:         "REG_DB_DEPTH_VIEW",
	REG_DB_RENDER_OVERRIDE:    "REG_DB_RENDER_OVERRIDE",
	REG_DB_RENDER_OVERRIDE2:   "REG_DB_RENDER_OVERRIDE2",
	REG_DB_HTILE_DATA_BASE:    "REG_DB_HTILE_DATA_BASE",
	REG_DB_DEPTH_BOUNDS_MIN:   "REG_DB_DEPTH_BOUNDS_MIN",
	REG_DB_DEPTH_BOUNDS_MAX:   "REG_DB_DEPTH_BOUNDS_MAX",
	REG_DB_STENCIL_CLEAR:      "REG_DB_STENCIL_CLEAR",
	REG_DB_DEPTH_CLEAR:        "REG_DB_DEPTH_CLEAR",
	REG_DB_DEPTH_INFO:         "REG_DB_DEPTH_INFO",
	REG_DB_Z_INFO:             "REG_DB_Z_INFO",
	REG_DB_STENCIL_INFO:       "REG_DB_STENCIL_INFO",
	REG_DB_Z_READ_BASE:        "REG_DB_Z_READ_BASE",
	REG_DB_STENCIL_READ_BASE:  "REG_DB_STENCIL_READ_BASE",
	REG_DB_Z_WRITE_BASE:       "REG_DB_Z_WRITE_BASE",
	REG_DB_STENCIL_WRITE_BASE: "REG_DB_STENCIL_WRITE_BASE",
	REG_DB_DEPTH_SIZE:         "REG_DB_DEPTH_SIZE",
	REG_DB_DEPTH_SLICE:        "REG_DB_DEPTH_SLICE",

	REG_DB_STENCIL_CONTROL:   "REG_DB_STENCIL_CONTROL",
	REG_DB_STENCILREFMASK:    "REG_DB_STENCILREFMASK",
	REG_DB_STENCILREFMASK_BF: "REG_DB_STENCILREFMASK_BF",

	REG_DB_DEPTH_CONTROL:        "REG_DB_DEPTH_CONTROL",
	REG_DB_EQAA:                 "REG_DB_EQAA",
	REG_DB_SHADER_CONTROL:       "REG_DB_SHADER_CONTROL",
	REG_DB_HTILE_SURFACE:        "REG_DB_HTILE_SURFACE",
	REG_DB_SRESULTS_COMP_STATE0: "REG_DB_SRESULTS_COMP_STATE0",
	REG_DB_SRESULTS_COMP_STATE1: "REG_DB_SRESULTS_COMP_STATE1",
	REG_DB_PRELOAD_CONTROL:      "REG_DB_PRELOAD_CONTROL",
	REG_DB_ALPHA_TO_MASK:        "REG_DB_ALPHA_TO_MASK",
}

func init() {
	colorBufferFields := map[uint32]string{
		0x00: "BASE", 0x01: "PITCH",
		0x02: "SLICE", 0x03: "VIEW",
		0x04: "INFO", 0x05: "ATTRIB",
		0x07: "CMASK", 0x08: "CMASK_SLICE",
		0x09: "FMASK", 0x0A: "FMASK_SLICE",
		0x0B: "CLEAR_WORD0", 0x0C: "CLEAR_WORD1",
	}
	for i := range uint32(0) {
		rtBase := REG_CB_COLOR0_BASE + (i * REG_CB_COLOR_STRIDE)
		for offset, suffix := range colorBufferFields {
			regAddr := rtBase + offset
			ContextRegisterNames[regAddr] = fmt.Sprintf("REG_CB_COLOR%d_%s", i, suffix)
		}
	}
}
