package gpu

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	hsp "github.com/CovenantSQL/HashStablePack/marshalhash"
)

// MarshalHash marshals for hash
func (z LiverpoolBindComputePipelineInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 0
	o = append(o, 0x80)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z LiverpoolBindComputePipelineInternal) Msgsize() (s int) {
	s = 1
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolBindPipelineInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 45
	o = append(o, 0xde, 0x0, 0x2d)
	o = hsp.AppendUint64(o, uint64(z.CbColorInfo0))
	o = hsp.AppendUint64(o, uint64(z.CbShaderMask))
	o = hsp.AppendUint32(o, z.DbDepthClearValue)
	o = hsp.AppendUint64(o, uint64(z.DbDepthControl))
	o = hsp.AppendUint64(o, uint64(z.DbDepthSize))
	o = hsp.AppendUint64(o, uint64(z.DbRenderControl))
	o = hsp.AppendUint64(o, uint64(z.DbShaderControl))
	o = hsp.AppendUint32(o, z.DbStencilClearValue)
	o = hsp.AppendUint64(o, uint64(z.DbStencilControl))
	o = hsp.AppendUint64(o, uint64(z.DbStencilRefMask))
	o = hsp.AppendUint64(o, uint64(z.DbStencilRefMaskBf))
	o = hsp.AppendUint64(o, uint64(z.DbZInfo))
	o = hsp.AppendUint64(o, uint64(z.DbZWriteBase))
	o = hsp.AppendUint32(o, z.MultiPrimIbResetIndex)
	o = hsp.AppendUint64(o, uint64(z.PaClVsOutCntl))
	o = hsp.AppendUint64(o, uint64(z.PaScAaConfig))
	o = hsp.AppendUint64(o, uint64(z.PaScAaMaskX0y0X1y0))
	o = hsp.AppendUint64(o, uint64(z.PaScAaMaskX0y1X1y1))
	o = hsp.AppendUint64(o, uint64(z.PaScModeCntl0))
	o = hsp.AppendUint64(o, uint64(z.PaSuLineCntl))
	o = hsp.AppendUint64(o, uint64(z.PaSuPolyOffsetBackOffset))
	o = hsp.AppendUint64(o, uint64(z.PaSuPolyOffsetBackScale))
	o = hsp.AppendUint64(o, uint64(z.PaSuPolyOffsetClamp))
	o = hsp.AppendUint64(o, uint64(z.PaSuPolyOffsetFrontOffset))
	o = hsp.AppendUint64(o, uint64(z.PaSuPolyOffsetFrontScale))
	o = hsp.AppendUint64(o, uint64(z.PaSuScModeCntl))
	o = hsp.AppendUint32(o, z.PrimType)
	o = hsp.AppendUint64(o, uint64(z.PsInControl))
	o = hsp.AppendUint64(o, uint64(z.PsInputAddress))
	o = hsp.AppendArrayHeader(o, uint32(32))
	for za0001 := range z.PsInputControls {
		o = hsp.AppendUint32(o, z.PsInputControls[za0001])
	}
	o = hsp.AppendUint64(o, uint64(z.RtAttrib))
	o = hsp.AppendUint64(o, uint64(z.RtBase))
	o = hsp.AppendUint64(o, uint64(z.RtBlendControl))
	o = hsp.AppendUint32(o, z.RtClearWord0)
	o = hsp.AppendUint32(o, z.RtClearWord1)
	o = hsp.AppendUint64(o, uint64(z.RtColorControl))
	o = hsp.AppendUint64(o, uint64(z.RtPitch))
	o = hsp.AppendUint32(o, z.RtSlice)
	o = hsp.AppendUint64(o, uint64(z.RtTargetMask))
	o = hsp.AppendUint64(o, uint64(z.RtView))
	o = hsp.AppendUint64(o, uint64(z.SpiShaderColFormat))
	o = hsp.AppendUint64(o, uint64(z.SpiShaderZFormat))
	o = hsp.AppendUint64(o, uint64(z.SpiVsOutConfig))
	o = hsp.AppendUint32(o, z.UserDataHash)
	o = hsp.AppendUint64(o, uint64(z.VgtMultiPrimIbResetEn))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolBindPipelineInternal) Msgsize() (s int) {
	s = 3 + hsp.Uint64Size + hsp.Uint64Size + 18 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 20 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 22 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 9 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + 16 + hsp.ArrayHeaderSize + (int(32) * (hsp.Uint32Size)) + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 13 + hsp.Uint32Size + 13 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + 8 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 13 + hsp.Uint32Size + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolBindResourcesInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 10
	o = append(o, 0x8a)
	if oTemp, err := z.ComputeContext.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	o = hsp.AppendUint64(o, uint64(z.ComputeShaderAddress))
	o = hsp.AppendUint64(o, uint64(z.EvalShaderAddress))
	if oTemp, err := z.FragmentContext.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	o = hsp.AppendUint64(o, uint64(z.FragmentShaderAddress))
	o = hsp.AppendUint64(o, uint64(z.GeometryShaderAddress))
	o = hsp.AppendUint64(o, uint64(z.HullShaderAddress))
	o = hsp.AppendUint32(o, z.UserDataHash)
	if oTemp, err := z.VertexContext.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	o = hsp.AppendUint64(o, uint64(z.VertexShaderAddress))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolBindResourcesInternal) Msgsize() (s int) {
	s = 1 + 15 + z.ComputeContext.Msgsize() + hsp.Uint64Size + hsp.Uint64Size + 16 + z.FragmentContext.Msgsize() + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 13 + hsp.Uint32Size + 14 + z.VertexContext.Msgsize() + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolDispatchInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 9
	o = append(o, 0x89)
	o = hsp.AppendUint32(o, z.ComputeShRsrc1)
	o = hsp.AppendUint32(o, z.ComputeShRsrc2)
	o = hsp.AppendUint32(o, z.DimX)
	o = hsp.AppendUint32(o, z.DimY)
	o = hsp.AppendUint32(o, z.DimZ)
	o = hsp.AppendUint32(o, z.ThreadX)
	o = hsp.AppendUint32(o, z.ThreadY)
	o = hsp.AppendUint32(o, z.ThreadZ)
	o = hsp.AppendUint32(o, z.UserDataHash)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolDispatchInternal) Msgsize() (s int) {
	s = 1 + 15 + hsp.Uint32Size + 15 + hsp.Uint32Size + 5 + hsp.Uint32Size + 5 + hsp.Uint32Size + 5 + hsp.Uint32Size + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size + 8 + hsp.Uint32Size + 13 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolDmaCopyInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint32(o, z.Count)
	o = hsp.AppendUint64(o, uint64(z.DstAddress))
	o = hsp.AppendUint64(o, uint64(z.SrcAddress))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolDmaCopyInternal) Msgsize() (s int) {
	s = 1 + 6 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolDrawInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 21
	o = append(o, 0xde, 0x0, 0x15)
	o = hsp.AppendUint32(o, z.DbDepthClearValue)
	o = hsp.AppendUint64(o, uint64(z.DbRenderControl))
	o = hsp.AppendUint32(o, z.DbStencilClearValue)
	o = hsp.AppendUint32(o, z.EvalShRsrc1)
	o = hsp.AppendUint32(o, z.EvalShRsrc2)
	o = hsp.AppendUint32(o, z.GeometryShRsrc1)
	o = hsp.AppendUint32(o, z.GeometryShRsrc2)
	o = hsp.AppendUint32(o, z.HullShRsrc1)
	o = hsp.AppendUint32(o, z.HullShRsrc2)
	o = hsp.AppendUint64(o, uint64(z.IndexBase))
	o = hsp.AppendUint32(o, z.IndexCount)
	o = hsp.AppendUint32(o, z.IndexOffset)
	o = hsp.AppendUint32(o, z.IndexType)
	o = hsp.AppendUint32(o, z.InstanceCount)
	o = hsp.AppendBool(o, z.IsIndexed)
	o = hsp.AppendUint32(o, z.PixelShRsrc1)
	o = hsp.AppendUint32(o, z.PixelShRsrc2)
	o = hsp.AppendUint32(o, z.PrimType)
	o = hsp.AppendUint32(o, z.UserDataHash)
	o = hsp.AppendUint32(o, z.VertexShRsrc1)
	o = hsp.AppendUint32(o, z.VertexShRsrc2)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolDrawInternal) Msgsize() (s int) {
	s = 3 + 18 + hsp.Uint32Size + hsp.Uint64Size + 20 + hsp.Uint32Size + 12 + hsp.Uint32Size + 12 + hsp.Uint32Size + 16 + hsp.Uint32Size + 16 + hsp.Uint32Size + 12 + hsp.Uint32Size + 12 + hsp.Uint32Size + hsp.Uint64Size + 11 + hsp.Uint32Size + 12 + hsp.Uint32Size + 10 + hsp.Uint32Size + 14 + hsp.Uint32Size + 10 + hsp.BoolSize + 13 + hsp.Uint32Size + 13 + hsp.Uint32Size + 9 + hsp.Uint32Size + 13 + hsp.Uint32Size + 14 + hsp.Uint32Size + 14 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolSetDynamicStateInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 32
	o = append(o, 0xde, 0x0, 0x20)
	o = hsp.AppendUint32(o, z.BlendAlpha)
	o = hsp.AppendUint32(o, z.BlendBlue)
	o = hsp.AppendUint32(o, z.BlendGreen)
	o = hsp.AppendUint32(o, z.BlendRed)
	o = hsp.AppendUint64(o, uint64(z.ClipControl))
	o = hsp.AppendFloat32(o, z.GbHorzClipAdj)
	o = hsp.AppendFloat32(o, z.GbHorzDiscAdj)
	o = hsp.AppendFloat32(o, z.GbVertClipAdj)
	o = hsp.AppendFloat32(o, z.GbVertDiscAdj)
	o = hsp.AppendUint32(o, z.GenericScissorBr)
	o = hsp.AppendUint64(o, uint64(z.GenericScissorTl))
	o = hsp.AppendUint64(o, uint64(z.HardwareScreenOffset))
	o = hsp.AppendUint32(o, z.LineStipplePattern)
	o = hsp.AppendUint32(o, z.LineStippleRepeatCount)
	o = hsp.AppendUint64(o, uint64(z.PaClVteCntl))
	o = hsp.AppendUint64(o, uint64(z.PaScModeCntl0))
	o = hsp.AppendUint64(o, uint64(z.PaSuScModeCntl))
	o = hsp.AppendUint32(o, z.ScissorBr)
	o = hsp.AppendUint64(o, uint64(z.ScissorTl))
	o = hsp.AppendUint32(o, z.VpScissorBr)
	o = hsp.AppendUint64(o, uint64(z.VpScissorTl))
	o = hsp.AppendFloat32(o, z.VpXOffset)
	o = hsp.AppendFloat32(o, z.VpXScale)
	o = hsp.AppendFloat32(o, z.VpYOffset)
	o = hsp.AppendFloat32(o, z.VpYScale)
	o = hsp.AppendFloat32(o, z.VpZMax)
	o = hsp.AppendFloat32(o, z.VpZMin)
	o = hsp.AppendFloat32(o, z.VpZOffset)
	o = hsp.AppendFloat32(o, z.VpZScale)
	o = hsp.AppendUint64(o, uint64(z.WindowOffset))
	o = hsp.AppendUint32(o, z.WindowScissorBr)
	o = hsp.AppendUint64(o, uint64(z.WindowScissorTl))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolSetDynamicStateInternal) Msgsize() (s int) {
	s = 3 + 11 + hsp.Uint32Size + 10 + hsp.Uint32Size + 11 + hsp.Uint32Size + 9 + hsp.Uint32Size + hsp.Uint64Size + 14 + hsp.Float32Size + 14 + hsp.Float32Size + 14 + hsp.Float32Size + 14 + hsp.Float32Size + 17 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + 19 + hsp.Uint32Size + 23 + hsp.Uint32Size + hsp.Uint64Size + hsp.Uint64Size + hsp.Uint64Size + 10 + hsp.Uint32Size + hsp.Uint64Size + 12 + hsp.Uint32Size + hsp.Uint64Size + 10 + hsp.Float32Size + 9 + hsp.Float32Size + 10 + hsp.Float32Size + 9 + hsp.Float32Size + 7 + hsp.Float32Size + 7 + hsp.Float32Size + 10 + hsp.Float32Size + 9 + hsp.Float32Size + hsp.Uint64Size + 16 + hsp.Uint32Size + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolWaitRegMemoryInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 4
	o = append(o, 0x84)
	o = hsp.AppendUint64(o, uint64(z.Address))
	o = hsp.AppendUint32(o, z.Function)
	o = hsp.AppendUint32(o, z.Mask)
	o = hsp.AppendUint32(o, z.Reference)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolWaitRegMemoryInternal) Msgsize() (s int) {
	s = 1 + hsp.Uint64Size + 9 + hsp.Uint32Size + 5 + hsp.Uint32Size + 10 + hsp.Uint32Size
	return
}

// MarshalHash marshals for hash
func (z *LiverpoolWriteDataInternal) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint64(o, uint64(z.Address))
	o = hsp.AppendArrayHeader(o, uint32(len(z.Data)))
	for za0001 := range z.Data {
		o = hsp.AppendUint32(o, z.Data[za0001])
	}
	o = hsp.AppendBool(o, z.Eop)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LiverpoolWriteDataInternal) Msgsize() (s int) {
	s = 1 + hsp.Uint64Size + 5 + hsp.ArrayHeaderSize + (len(z.Data) * (hsp.Uint32Size)) + 4 + hsp.BoolSize
	return
}
