package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type Signature struct {
	FuncType   string
	Params     []Param
	ReturnType string
}

type Param struct {
	Name string
	Type string
}

var regNames = []string{"DI", "SI", "DX", "CX", "R8", "R9"}

const templateSrc = `// Code generated by stub_gen.go; DO NOT EDIT.

package elf

import (
	"unsafe"

	"github.com/LamkasDev/sharkie/cmd/asm"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/fs"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/time"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/app_content"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/module"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/tcb"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/video"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/user"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/system_service"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/save_data"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/semaphore"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/pad"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/net"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/user_service"
	. "github.com/LamkasDev/sharkie/cmd/lib_structs/pthread"
)

func CreateDispatcher(goFn any) asm.StubDispatcher {
	switch fn := goFn.(type) {
{{- range $sig := .}}
	case {{$sig.FuncType}}:
		return func(ctx *asm.RegContext) uintptr {
{{- range $i, $p := $sig.Params}}
	{{- if hasPrefix $p.Name "stack"}}
			arg{{add $i 1}} := *(*{{$p.Type}})(unsafe.Add(unsafe.Pointer(ctx), asm.RegContextSize+{{regOffset $i}}))
	{{- end}}
{{- end}}
{{- if hasPrefix $sig.ReturnType "*"}}
			return uintptr(unsafe.Pointer(fn({{range $i, $p := $sig.Params}}{{if hasPrefix $p.Name "stack"}}arg{{add $i 1}}{{else if eq $p.Type "uintptr"}}ctx.{{$p.Name}}{{else if hasPrefix $p.Type "*" }}({{$p.Type}})(unsafe.Pointer(ctx.{{$p.Name}})){{else}}{{$p.Type}}(ctx.{{$p.Name}}){{end}}{{if ne $i (len $sig.Params | minusOne)}}, {{end}}{{end}})))		}
{{- else}}
			return uintptr(fn({{range $i, $p := $sig.Params}}{{if hasPrefix $p.Name "stack"}}arg{{add $i 1}}{{else if eq $p.Type "uintptr"}}ctx.{{$p.Name}}{{else if hasPrefix $p.Type "*" }}({{$p.Type}})(unsafe.Pointer(ctx.{{$p.Name}})){{else}}{{$p.Type}}(ctx.{{$p.Name}}){{end}}{{if ne $i (len $sig.Params | minusOne)}}, {{end}}{{end}}))		}
{{- end}}
{{- end}}
	default:
		panic("unsupported function type")
	}
}
`

func main() {
	// Parse cmd/lib for stub files.
	fset := token.NewFileSet()
	packages := make(map[string]*ast.Package)
	err := filepath.Walk("../lib", func(path string, info os.FileInfo, err error) error {
		if err != nil || !info.IsDir() {
			return nil
		}
		pkgs, err := parser.ParseDir(fset, path, nil, 0)
		if err != nil {
			return err
		}
		for _, pkg := range pkgs {
			packages[path] = pkg
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

	// Collect signatures from stub files.
	sigsMap := make(map[string]Signature)
	sigsMap["func() uintptr"] = Signature{FuncType: "func() uintptr", Params: nil, ReturnType: "uintptr"}
	for _, pkg := range packages {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}

				var fnArg ast.Expr
				if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
					id, ok := sel.X.(*ast.Ident)
					if !ok || id.Name != "elf" {
						return true
					}
					if sel.Sel.Name != "RegisterStub" && sel.Sel.Name != "RegisterMinecraftStub" && sel.Sel.Name != "RegisterAssemblyStub" {
						return true
					}
					if len(call.Args) >= 3 {
						fnArg = call.Args[2]
					}
				} else if id, ok := call.Fun.(*ast.Ident); ok {
					if id.Name != "RegisterPosixStub" {
						return true
					}
					if len(call.Args) >= 2 {
						fnArg = call.Args[1]
					}
				}
				if fnArg == nil {
					return true
				}

				if fnId, ok := fnArg.(*ast.Ident); ok {
					// Search by name in the same package.
					for _, pfile := range pkg.Files {
						for _, d := range pfile.Decls {
							fd, ok := d.(*ast.FuncDecl)
							if !ok || fd.Name.Name != fnId.Name {
								continue
							}
							sig := extractSignature(fd.Type)
							sigsMap[sig.FuncType] = sig
						}
					}
				} else if fnLit, ok := fnArg.(*ast.FuncLit); ok {
					sig := extractSignature(fnLit.Type)
					sigsMap[sig.FuncType] = sig
				}

				return true
			})
		}
	}

	// Sort for deterministic output.
	var signatures []Signature
	for _, sig := range sigsMap {
		signatures = append(signatures, sig)
	}
	sort.Slice(signatures, func(i, j int) bool {
		return signatures[i].FuncType < signatures[j].FuncType
	})

	// Generate go file.
	genTemplate := template.Must(template.New("gen").Funcs(template.FuncMap{
		"hasPrefix": strings.HasPrefix,
		"minusOne":  func(n int) int { return n - 1 },
		"add":       func(a, b int) int { return a + b },
		"regOffset": func(i int) int { return (i - 5) * 8 },
	}).Parse(templateSrc))
	var buffer bytes.Buffer
	if err := genTemplate.Execute(&buffer, signatures); err != nil {
		panic(err)
	}

	// Format and write file.
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: gofmt failed: %v\n", err)
		formatted = buffer.Bytes()
	}
	if err = os.WriteFile("../elf/stub_dispatcher.go", formatted, 0644); err != nil {
		panic(err)
	}
}

func extractSignature(ft *ast.FuncType) Signature {
	var params []Param
	paramTypes := []string{}
	if ft.Params != nil {
		for _, field := range ft.Params.List {
			typ := exprToString(field.Type)
			count := len(field.Names)
			if count == 0 {
				count = 1
			}
			for i := 0; i < count; i++ {
				paramTypes = append(paramTypes, typ)
				idx := len(params)
				name := ""
				if idx < len(regNames) {
					name = regNames[idx]
				} else {
					name = fmt.Sprintf("stack%d", idx-len(regNames))
				}
				params = append(params, Param{Name: name, Type: typ})
			}
		}
	}

	var results []string
	if ft.Results != nil {
		for _, field := range ft.Results.List {
			typ := exprToString(field.Type)
			count := len(field.Names)
			if count == 0 {
				count = 1
			}
			for i := 0; i < count; i++ {
				results = append(results, typ)
			}
		}
	}

	resStr := ""
	funcResStr := ""
	if len(results) == 1 {
		resStr = results[0]
		funcResStr = " " + results[0]
	} else if len(results) > 1 {
		resStr = "(" + strings.Join(results, ", ") + ")"
		funcResStr = " " + resStr
	}

	return Signature{
		FuncType:   fmt.Sprintf("func(%s)%s", strings.Join(paramTypes, ", "), funcResStr),
		Params:     params,
		ReturnType: resStr,
	}
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	default:
		return "uintptr"
	}
}
